import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext(null);

const translations = {
  es: {
    // Navbar
    'navbar.controlPanel': 'Panel de control',
    'navbar.login': 'Iniciar sesión',
    'navbar.register': 'Comenzar',
    'navbar.logout': 'Cerrar sesión',
    'lang.es': 'Español',
    'lang.en': 'English',

    // Login
    'login.title': 'Bienvenido de nuevo',
    'login.subtitle': 'Inicia sesión para gestionar tus encuestas',
    'login.username': 'Usuario',
    'login.usernamePlaceholder': 'Tu nombre de usuario',
    'login.password': 'Contraseña',
    'login.forgotPassword': '¿Olvidaste tu contraseña?',
    'login.submit': 'Iniciar sesión',
    'login.submitting': 'Iniciando sesión...',
    'login.noAccount': '¿No tienes cuenta?',
    'login.registerLink': 'Regístrate aquí',
    'login.error': 'Error al iniciar sesión. Verifica tus credenciales.',

    // Forgot password
    'forgotPwd.title': 'Recuperar contraseña',
    'forgotPwd.description': 'Ingresa tu correo y te enviaremos un enlace para restablecer tu contraseña.',
    'forgotPwd.email': 'Correo electrónico',
    'forgotPwd.placeholder': 'tu@correo.com',
    'forgotPwd.cancel': 'Cancelar',
    'forgotPwd.send': 'Enviar enlace',
    'forgotPwd.success': 'Si existe una cuenta con ese correo, recibirás un enlace en breve.',
    'forgotPwd.close': 'Cerrar',

    // Register
    'register.title': 'Crear cuenta',
    'register.subtitle': 'Únete a Pooly y comienza a crear encuestas',
    'register.username': 'Usuario',
    'register.usernamePlaceholder': 'Elige un nombre de usuario',
    'register.email': 'Correo electrónico',
    'register.emailPlaceholder': 'tu@correo.com',
    'register.password': 'Contraseña',
    'register.confirmPassword': 'Confirmar contraseña',
    'register.submit': 'Crear cuenta',
    'register.submitting': 'Creando cuenta...',
    'register.hasAccount': '¿Ya tienes cuenta?',
    'register.loginLink': 'Inicia sesión aquí',
    'register.errorPasswordMatch': 'Las contraseñas no coinciden',
    'register.errorUserExists': 'Este usuario ya existe. Intenta con otro nombre de usuario.',
    'register.errorGeneric': 'Error en el registro. Inténtalo de nuevo.',
    'register.errorAutoLogin': 'Cuenta creada, pero el inicio de sesión automático falló. Por favor inicia sesión manualmente.',

    // Admin Dashboard
    'admin.loading': 'Cargando tu panel de control...',
    'admin.hello': 'Hola, {{username}}',
    'admin.subtitle': 'Gestiona tus encuestas y analiza las respuestas de tu comunidad.',
    'admin.statTotal': 'Encuestas totales',
    'admin.statResponses': 'Respuestas totales',
    'admin.statActive': 'Encuestas activas',
    'admin.statAvg': 'Promedio respuestas',
    'admin.errorLoad': 'No se pudieron cargar tus eventos.',
    'admin.errorDemo': 'Mostrando datos de demostración',
    'admin.deleteSuccess': 'La encuesta se eliminó correctamente.',
    'admin.deleteError': 'No se pudo eliminar la encuesta. Intenta de nuevo.',
    'admin.deleteErrorGeneric': 'Error al eliminar la encuesta. Intenta de nuevo.',
    'admin.sectionTitle': 'Mis encuestas',
    'admin.survey': 'encuesta',
    'admin.surveys': 'encuestas',
    'admin.newSurvey': 'Nueva encuesta',
    'admin.emptyTitle': 'Aún no tienes encuestas',
    'admin.emptyDesc': 'Crea tu primera encuesta para comenzar a recolectar opiniones de tu comunidad.',
    'admin.createFirst': 'Crear mi primera encuesta',
    'admin.tapHint': 'Toca para ver detalles',
    'admin.deleteModalTitle': 'Eliminar encuesta',
    'admin.deleteModalMessage': '¿Estás seguro de que deseas eliminar la encuesta "{{name}}"?',
    'admin.deleteWarning': 'Esta acción no se puede deshacer. Se eliminarán:',
    'admin.deleteItem1': 'Todas las preguntas de la encuesta',
    'admin.deleteItem2': 'Todas las respuestas recibidas ({{count}})',
    'admin.deleteItem3': 'Todos los reportes de análisis generados',
    'admin.cancel': 'Cancelar',
    'admin.delete': 'Eliminar',
    'admin.deleting': 'Eliminando...',

    // Event status labels
    'status.ended': 'Finalizada',
    'status.lastDay': 'Último día',
    'status.closing': 'Por cerrar',
    'status.active': 'Activa',
    'status.endedDays': 'Terminó hace {{days}} días',
    'status.endsToday': 'Termina hoy',
    'status.daysLeft': '{{days}} días restantes',

    // Event Details
    'eventDetails.loading': 'Cargando detalles del evento...',
    'eventDetails.back': '← Volver al panel',
    'eventDetails.endDate': 'Finaliza: {{date}}',
    'eventDetails.totalResponses': '{{count}} respuestas totales',
    'eventDetails.analyzeTitle': 'Analizar con IA',
    'eventDetails.analyzing': 'Analizando...',
    'eventDetails.shareTitle': 'Enlace para compartir',
    'eventDetails.shareSubtitle': 'Comparte este enlace con los participantes',
    'eventDetails.shareGenerating': 'Generando enlace...',
    'eventDetails.shareCopy': 'Copiar',
    'eventDetails.shareCopied': '✓ Copiado',
    'eventDetails.shareHint': 'Las respuestas son completamente anónimas. Los participantes no necesitan crear cuenta.',
    'eventDetails.tabResponses': 'Respuestas',
    'eventDetails.tabReports': 'Reportes IA',
    'eventDetails.tabStatus': 'Status',
    'eventDetails.noResponses': 'Sin respuestas aún.',
    'eventDetails.responses': 'respuestas',
    'eventDetails.errorLoad': 'No se pudieron cargar los detalles del evento.',

    // Reports tab
    'reports.title': 'Análisis de Respuestas',
    'reports.subtitle': '{{count}} categorías identificadas por IA',
    'reports.subtitleEmpty': 'Los reportes aparecerán aquí después del análisis',
    'reports.refresh': '↻ Actualizar',
    'reports.loading': 'Cargando...',
    'reports.loadingState': 'Cargando reportes...',
    'reports.error': 'No se pudieron cargar los reportes.',
    'reports.errorDemo': 'Mostrando datos de demostración',
    'reports.emptyTitle': 'Sin reportes disponibles',
    'reports.emptyDesc': 'Genera un análisis con IA para obtener insights de las respuestas.',
    'reports.analyzeBtn': 'Analizar con IA',
    'reports.generated': 'Generado: {{date}}',
    'reports.examples': 'Ejemplos:',
    'reports.mentions': 'menciones',
    'reports.ofTotal': 'del total',

    // Sentiment / Urgency
    'sentiment.positive': 'Positivo',
    'sentiment.negative': 'Negativo',
    'sentiment.neutral': 'Neutral',
    'urgency.high': 'Alta',
    'urgency.medium': 'Media',
    'urgency.low': 'Baja',
    'urgency.label': 'Urgencia: {{level}}',

    // Jobs / Status tab
    'jobs.title': 'Estado de Análisis',
    'jobs.subtitle': '{{count}} trabajos registrados',
    'jobs.subtitleEmpty': 'Los trabajos de análisis aparecerán aquí',
    'jobs.loading': 'Cargando trabajos...',
    'jobs.error': 'No es posible recuperar la información en este momento.',
    'jobs.emptyTitle': 'Sin trabajos registrados',
    'jobs.emptyDesc': 'Cuando inicies un análisis con IA, podrás ver su progreso aquí.',
    'jobs.colId': 'ID',
    'jobs.colStatus': 'Estado',
    'jobs.colMessage': 'Mensaje',
    'jobs.colStarted': 'Iniciado',
    'jobs.colUpdated': 'Actualizado',
    'jobs.statusCompleted': 'Completado',
    'jobs.statusRunning': 'En proceso',
    'jobs.statusError': 'Error',

    // Analyze modal
    'analyzeModal.title': 'Iniciar análisis con IA',
    'analyzeModal.cancel': 'Cancelar',
    'analyzeModal.confirm': 'Iniciar análisis',
    'analyzeModal.statusSuccess': '¡Análisis iniciado exitosamente! Puedes monitorear el progreso en la sección Status.',
    'analyzeModal.statusError': 'Error al iniciar el análisis. Intenta de nuevo.',

    // Create Event
    'create.back': '← Volver al panel',
    'create.title': 'Crear nueva encuesta',
    'create.step': 'Paso {{step}} de 2',
    'create.step1Label': 'Detalles de la encuesta',
    'create.step2Label': 'Agregar preguntas',
    'create.name': 'Nombre de la encuesta',
    'create.namePlaceholder': 'ej. Movilidad Urbana 2026',
    'create.description': 'Descripción',
    'create.descPlaceholder': 'Describe el propósito de esta encuesta...',
    'create.endDate': 'Fecha de cierre',
    'create.next': 'Siguiente: Agregar preguntas',
    'create.errorNoDate': 'Por favor selecciona una fecha de cierre para la encuesta.',
    'create.errorPastDate': 'La fecha de cierre debe ser una fecha futura.',
    'create.questionsLabel': 'Preguntas de la encuesta',
    'create.questionsHint': 'Escribe preguntas abiertas para que los participantes puedan responder libremente.',
    'create.questionPlaceholder': 'Escribe la pregunta {{num}}',
    'create.addQuestion': '+ Agregar otra pregunta',
    'create.questionRequired': 'Obligatoria',
    'create.questionOptional': 'Opcional',
    'create.prev': 'Anterior',
    'create.submit': 'Crear encuesta',
    'create.submitting': 'Creando...',
    'create.errorNoQuestions': 'Por favor agrega al menos una pregunta.',
    'create.errorGeneric': 'Error al crear la encuesta.',
    'tips.step1.title': 'Consejos para tu encuesta',
    'tips.step1.tip1.title': 'Título claro y específico',
    'tips.step1.tip1.desc': 'Un buen título ayuda a los participantes a entender el tema. Ej: "Movilidad Urbana 2026" en lugar de "Encuesta".',
    'tips.step1.tip2.title': 'Descripción motivadora',
    'tips.step1.tip2.desc': 'Explica por qué es importante participar y cómo se usarán las respuestas para tomar decisiones.',
    'tips.step1.tip3.title': 'Tiempo suficiente',
    'tips.step1.tip3.desc': 'Da al menos 1-2 semanas para que los participantes puedan responder con calma.',
    'tips.step1.highlight': 'Las encuestas con descripciones claras tienen 40% más participación.',
    'tips.step2.title': 'Crea preguntas efectivas',
    'tips.step2.tip1.title': 'Preguntas abiertas',
    'tips.step2.tip1.desc': 'Permiten respuestas detalladas que nuestra IA puede analizar para encontrar patrones y tendencias.',
    'tips.step2.tip2.title': 'Evita sesgos',
    'tips.step2.tip2.desc': 'No induzcas respuestas. "¿Qué opinas del transporte?" es mejor que "¿No crees que el transporte es malo?"',
    'tips.step2.tip3.title': 'Una idea por pregunta',
    'tips.step2.tip3.desc': 'Divide preguntas complejas. Es más fácil analizar "¿Qué medio usas?" y "¿Qué mejorarías?" por separado.',
    'tips.step2.highlight': 'Nuestra IA analiza las respuestas para identificar temas, sentimiento y prioridades automáticamente.',
    'tips.examples.title': 'Ejemplos de buenas preguntas',
    'tips.examples.item1': '¿Cuál es el principal problema que enfrentas con...?',
    'tips.examples.item2': '¿Qué cambiarías si pudieras...?',
    'tips.examples.item3': '¿Cómo te afecta actualmente...?',

    // Edit Event / Questions
    'editEvent.editBtn': 'Editar Evento',
    'editEvent.saveBtn': 'Guardar',
    'editEvent.cancelBtn': 'Cancelar',
    'editEvent.saving': 'Guardando...',
    'editEvent.addQuestion': '+ Agregar pregunta',
    'editEvent.saveSuccess': 'Guardado con éxito',
    'editEvent.saveError': 'Error al guardar la información',
    'editEvent.newQuestionsLabel': 'Nuevas preguntas',
    'editEvent.existingQuestionsLabel': 'Preguntas existentes',
    'editEvent.questionPlaceholder': 'Escribe la nueva pregunta {{num}}',

    // Settings
    'settings.back': '← Volver al panel',
    'settings.title': 'Configuración',
    'settings.subtitle': 'Detalles de tu cuenta',
    'settings.sectionTitle': 'Información de usuario',
    'settings.username': 'Nombre de usuario',
    'settings.email': 'Correo electrónico',
    'settings.role': 'Rol',
    'settings.roleDefault': 'Usuario',

    // Landing page
    'landing.nav.product': 'Producto',
    'landing.nav.how': 'Cómo funciona',
    'landing.nav.customers': 'Clientes',
    'landing.nav.pricing': 'Precios',
    'landing.hero.kicker': 'Plataforma de encuestas con IA',
    'landing.hero.title1': 'Encuestas que piensan.',
    'landing.hero.title2': 'Respuestas que importan.',
    'landing.hero.sub': 'Pooly usa inteligencia artificial para ayudarte a crear encuestas más inteligentes, llegar a la audiencia correcta y convertir respuestas en decisiones — más rápido que nunca.',
    'landing.hero.cta1': 'Empezar gratis',
    'landing.hero.cta2': 'Ver cómo funciona',
    'landing.hero.note': 'Sin tarjeta de crédito · Plan gratuito para siempre',
    'landing.hero.stat1.value': '2,847',
    'landing.hero.stat1.label': 'Respuestas hoy',
    'landing.hero.stat1.trend': '↑ 18% esta semana',
    'landing.hero.stat2.label': 'Tasa de finalización',
    'landing.hero.stat2.trend': '↑ vs. promedio del sector',
    'landing.f1.eyebrow': 'Constructor de encuestas con IA',
    'landing.f1.title': 'De la idea a la encuesta en segundos',
    'landing.f1.body': 'Describe lo que quieres aprender y el motor de IA de Pooly genera una encuesta completa y optimizada — con lógica de preguntas inteligente, ramificaciones y detección de sesgos integrada.',
    'landing.f1.li1': 'Genera encuestas completas desde un solo prompt',
    'landing.f1.li2': 'Detecta y corrige preguntas tendenciosas automáticamente',
    'landing.f1.li3': 'Lógica de salto inteligente y ramificación condicional',
    'landing.f1.li4': 'Soporte multilingüe desde el primer momento',
    'landing.f1.cta': 'Crea tu primera encuesta →',
    'landing.midcta.h3': '¿Listo para escuchar lo que tus clientes realmente piensan?',
    'landing.midcta.p': 'Únete a más de 50,000 equipos que ya usan Pooly para tomar decisiones más inteligentes.',
    'landing.midcta.btn': 'Comenzar gratis →',
    'landing.f2.eyebrow': 'Análisis en tiempo real',
    'landing.f2.title': 'Las respuestas se convierten en insights automáticamente',
    'landing.f2.body': 'Observa las respuestas en tiempo real. La IA de Pooly detecta tendencias, cambios de sentimiento y temas clave a medida que llegan las respuestas — sin análisis manual.',
    'landing.f2.li1': 'Panel de respuestas en vivo con filtros',
    'landing.f2.li2': 'Resumen generado por IA de respuestas abiertas',
    'landing.f2.li3': 'Reportes exportables (CSV, PDF, Notion)',
    'landing.f2.cta': 'Ver demo de análisis →',
    'landing.stats.l1': 'Equipos usando Pooly',
    'landing.stats.l2': 'Respuestas recopiladas',
    'landing.stats.l3': 'Tasa de finalización promedio',
    'landing.stats.l4': 'Más rápido que de forma manual',
    'landing.f3.eyebrow': 'Biblioteca de plantillas',
    'landing.f3.title': 'Más de 100 plantillas expertas para comenzar',
    'landing.f3.body': 'Desde NPS y CSAT hasta compromiso del empleado e investigación de mercado — cada plantilla está respaldada por investigación y lista para personalizar.',
    'landing.f3.li1': 'Categorizadas por sector y caso de uso',
    'landing.f3.li2': 'Branding completamente personalizable',
    'landing.f3.li3': 'Publicación con un clic por enlace, email o embed',
    'landing.f3.cta': 'Ver plantillas →',
    'landing.f4.eyebrow': 'Hecho para equipos',
    'landing.f4.title': 'Todo el equipo, en la misma página',
    'landing.f4.body': 'Colabora en encuestas, comparte resultados con stakeholders y gestiona permisos — todo en un solo lugar. Personas reales, flujos de trabajo reales.',
    'landing.f4.li1': 'Espacios de trabajo multiusuario con acceso por roles',
    'landing.f4.li2': 'Resultados compartidos y anotaciones colaborativas',
    'landing.f4.li3': 'SSO, registros de auditoría y cumplimiento empresarial',
    'landing.f4.cta': 'Explorar funciones del equipo',
    'landing.hiw.eyebrow': 'Cómo funciona',
    'landing.hiw.title': 'Tres pasos para mejores respuestas',
    'landing.hiw.body': 'Del prompt a la publicación en menos de dos minutos. Pooly se encarga de lo difícil para que puedas enfocarte en los insights.',
    'landing.hiw.s1.title': 'Describe tu objetivo',
    'landing.hiw.s1.body': 'Dile a Pooly qué quieres aprender — en español natural. No se necesita experiencia en diseño de encuestas.',
    'landing.hiw.s2.title': 'Revisa y personaliza',
    'landing.hiw.s2.body': 'La IA genera tu encuesta al instante. Edita preguntas, agrega tu marca y configura la lógica de distribución.',
    'landing.hiw.s3.title': 'Comparte y analiza',
    'landing.hiw.s3.body': 'Envía por enlace, email o embed. Los insights aparecen automáticamente conforme llegan las respuestas.',
    'landing.hiw.cta': 'Pruébalo gratis →',
    'landing.t.eyebrow': 'Historias de clientes',
    'landing.t.title': 'La confianza de quienes necesitan respuestas reales',
    'landing.t.q1': 'Pooly redujo a la mitad el tiempo de configuración de nuestras encuestas. Las sugerencias de IA son realmente útiles — detectó preguntas tendenciosas que nosotros no notamos.',
    'landing.t.n1': 'Sara Velázquez',
    'landing.t.r1': 'Jefa de Investigación, Meridian',
    'landing.t.q2': 'Hicimos nuestra primera encuesta NPS a los 10 minutos de registrarnos. La tasa de respuesta fue 40% mayor que con nuestra herramienta anterior — el diseño importa mucho.',
    'landing.t.n2': 'Marcus Chen',
    'landing.t.r2': 'Product Manager, Northvale',
    'landing.t.q3': 'Los análisis en tiempo real son increíbles. Compartí un panel en vivo con nuestra junta mientras la encuesta seguía activa — quedaron impresionados.',
    'landing.t.n3': 'Aisha Okonkwo',
    'landing.t.r3': 'Directora de Estrategia, Arkon Labs',
    'landing.p.eyebrow': 'Precios',
    'landing.p.title': 'Precios simples y honestos',
    'landing.p.body': 'Comienza gratis. Actualiza cuando necesites más potencia. Sin cargos ocultos.',
    'landing.p.free.plan': 'Gratis',
    'landing.p.free.period': 'para siempre',
    'landing.p.free.desc': 'Ideal para personas que exploran las encuestas con IA.',
    'landing.p.free.li1': '3 encuestas activas',
    'landing.p.free.li2': '100 respuestas / mes',
    'landing.p.free.li3': 'Constructor de encuestas con IA',
    'landing.p.free.li4': 'Análisis básico',
    'landing.p.free.btn': 'Comenzar',
    'landing.p.pro.plan': 'Pro',
    'landing.p.pro.badge': 'Más popular',
    'landing.p.pro.period': 'por mes',
    'landing.p.pro.desc': 'Para equipos que necesitan encuestas ilimitadas e IA avanzada.',
    'landing.p.pro.li1': 'Encuestas ilimitadas',
    'landing.p.pro.li2': '10,000 respuestas / mes',
    'landing.p.pro.li3': 'Análisis de IA avanzado',
    'landing.p.pro.li4': 'Branding personalizado',
    'landing.p.pro.li5': 'Exportaciones CSV y PDF',
    'landing.p.pro.li6': 'Soporte prioritario',
    'landing.p.pro.btn': 'Iniciar prueba gratis',
    'landing.p.ent.plan': 'Empresa',
    'landing.p.ent.price': 'Personalizado',
    'landing.p.ent.period': 'contáctenos',
    'landing.p.ent.desc': 'Para grandes organizaciones con requisitos de seguridad y cumplimiento.',
    'landing.p.ent.li1': 'Todo ilimitado',
    'landing.p.ent.li2': 'SSO y registros de auditoría',
    'landing.p.ent.li3': 'Cumplimiento empresarial',
    'landing.p.ent.li4': 'Onboarding dedicado',
    'landing.p.ent.li5': 'Garantía de SLA',
    'landing.p.ent.li6': 'Integraciones personalizadas',
    'landing.p.ent.btn': 'Contactar ventas',
    'landing.cta.title': 'Empieza a tomar decisiones con confianza.',
    'landing.cta.body': 'Únete a más de 50,000 equipos que crean encuestas más inteligentes con Pooly.',
    'landing.cta.btn1': 'Comenzar gratis →',
    'landing.cta.btn2': 'Iniciar sesión',
    'landing.footer.tagline': 'Encuestas con IA que ayudan a los equipos a tomar mejores decisiones.',
    'landing.footer.col1': 'Producto',
    'landing.footer.col2': 'Recursos',
    'landing.footer.col3': 'Aprender',
    'landing.footer.col4': 'Acerca de',
    'landing.footer.p1': 'Constructor de encuestas',
    'landing.footer.p2': 'Análisis',
    'landing.footer.p3': 'Plantillas',
    'landing.footer.p4': 'Precios',
    'landing.footer.r1': 'Documentación',
    'landing.footer.r2': 'Referencia de API',
    'landing.footer.r3': 'Integraciones',
    'landing.footer.r4': 'Estado',
    'landing.footer.l1': 'Blog',
    'landing.footer.l2': 'Guías de encuestas',
    'landing.footer.l3': 'Casos de estudio',
    'landing.footer.l4': 'Webinars',
    'landing.footer.a1': 'Empresa',
    'landing.footer.a2': 'Empleos',
    'landing.footer.a3': 'Prensa',
    'landing.footer.a4': 'Contacto',
    'landing.footer.copy': '© 2025 Pooly. Todos los derechos reservados.',
    'landing.footer.privacy': 'Política de privacidad',
    'landing.footer.terms': 'Términos de servicio',
    'landing.footer.cookies': 'Cookies',

    // Public Gallery
    'gallery.badge': 'Plataforma de participación ciudadana',
    'gallery.heroTitle1': 'Transforma miles de voces en',
    'gallery.heroTitle2': 'insights accionables',
    'gallery.heroDesc': 'Crea encuestas, recolecta opiniones de tu comunidad y obtén análisis automático con IA. Descubre patrones, sentimientos y prioridades sin categorías predefinidas.',
    'gallery.ctaStart': 'Comenzar gratis',
    'gallery.ctaLogin': 'Ya tengo cuenta',
    'gallery.howTitle': 'Cómo funciona',
    'gallery.howDesc': 'Tres pasos simples para convertir la retroalimentación de tu comunidad en decisiones informadas.',
    'gallery.step1Title': 'Crea tu encuesta',
    'gallery.step1Desc': 'Define las preguntas abiertas que quieres hacer a tu comunidad. Sin límites de opciones predefinidas.',
    'gallery.step2Title': 'Comparte el enlace',
    'gallery.step2Desc': 'Distribuye el enlace único. Los participantes responden de forma anónima desde cualquier dispositivo.',
    'gallery.step3Title': 'Obtén insights',
    'gallery.step3Desc': 'Nuestra IA agrupa respuestas, identifica temas emergentes y analiza el sentimiento automáticamente.',
    'gallery.aiTitle': 'Potenciado por inteligencia artificial',
    'gallery.aiDesc': 'Tecnología avanzada de Procesamiento de Lenguaje para entender lo que tu comunidad realmente necesita.',
    'gallery.feature1Title': 'Descubrimiento automático',
    'gallery.feature1Desc': 'Traduce miles de voces individuales en categorías claras sin necesidad de definirlas previamente. La IA encuentra los patrones por ti.',
    'gallery.feature2Title': 'Análisis de prioridades',
    'gallery.feature2Desc': 'Clasifica los temas por importancia, sentimiento y urgencia. Toma decisiones basadas en datos reales de tu comunidad.',
    'gallery.feature3Title': 'Multilingüe',
    'gallery.feature3Desc': 'Soporte para más de 50 idiomas. Recibe respuestas en cualquier idioma y obtén análisis unificados y coherentes.',
    'gallery.useCasesTitle': 'Casos de uso',
    'gallery.useCasesDesc': 'Desde planeación urbana hasta investigación de mercado, Pooly se adapta a tus necesidades.',
    'gallery.useCase1Title': 'Planeación urbana',
    'gallery.useCase1Desc': 'Recolecta retroalimentación ciudadana sobre infraestructura, parques y servicios públicos. Visualiza el futuro de tu ciudad a través de la colaboración comunitaria.',
    'gallery.useCase2Title': 'Eventos y conferencias',
    'gallery.useCase2Desc': 'Entiende la satisfacción de los asistentes y recopila sugerencias de mejora. Desde conferencias hasta festivales, clarifica cada voz.',
    'gallery.useCase3Title': 'Investigación de producto',
    'gallery.useCase3Desc': 'Prueba nuevas ideas directamente con tu comunidad e itera rápidamente. Insights que impulsan innovación significativa.',
    'gallery.statLang': 'Idiomas soportados',
    'gallery.statAi': 'Análisis inteligente',
    'gallery.statAnon': 'Anónimo y seguro',
    'gallery.ctaTitle': 'Empieza a escuchar a tu comunidad',
    'gallery.ctaDesc': 'Crea tu primera encuesta en minutos. Sin tarjeta de crédito requerida.',
    'gallery.ctaBtn': 'Crear cuenta gratis',
    'gallery.footer': '© 2025 Pooly. Plataforma de participación ciudadana.',

    // Public Survey
    'survey.loading': 'Cargando encuesta...',
    'survey.notFound': 'Encuesta no encontrada',
    'survey.notFoundDesc': 'El enlace que seguiste no es válido o la encuesta ya no está disponible.',
    'survey.goToPooly': 'Ir a Pooly',
    'survey.progressBadge': '{{answered}} de {{total}}',
    'survey.question': 'Pregunta {{num}}',
    'survey.placeholder': 'Escribe tu respuesta aquí...',
    'survey.anonymous': 'Tus respuestas son anónimas y seguras',
    'survey.submit': 'Enviar',
    'survey.submitting': 'Enviando...',
    'survey.successTitle': '¡Gracias por participar!',
    'survey.successDesc': 'Tus respuestas han sido registradas exitosamente.',
    'survey.successNote': 'Tu opinión es valiosa y nos ayuda a tomar mejores decisiones.',
    'survey.errorAtLeastOne': 'Por favor responde al menos una pregunta.',
    'survey.errorMaxChars': 'Las respuestas {{nums}} no pueden superar los 500 caracteres.',
    'survey.errorSubmit': 'Error al enviar las respuestas.',
    'survey.errorLoad': 'No se pudo cargar la encuesta.',
  },

  en: {
    // Navbar
    'navbar.controlPanel': 'Control Panel',
    'navbar.login': 'Log in',
    'navbar.register': 'Get started',
    'navbar.logout': 'Log out',
    'lang.es': 'Español',
    'lang.en': 'English',

    // Login
    'login.title': 'Welcome back',
    'login.subtitle': 'Sign in to manage your surveys',
    'login.username': 'Username',
    'login.usernamePlaceholder': 'Your username',
    'login.password': 'Password',
    'login.forgotPassword': 'Forgot your password?',
    'login.submit': 'Sign in',
    'login.submitting': 'Signing in...',
    'login.noAccount': "Don't have an account?",
    'login.registerLink': 'Sign up here',
    'login.error': 'Login failed. Please check your credentials.',

    // Forgot password
    'forgotPwd.title': 'Reset password',
    'forgotPwd.description': 'Enter your email and we will send you a reset link.',
    'forgotPwd.email': 'Email address',
    'forgotPwd.placeholder': 'you@email.com',
    'forgotPwd.cancel': 'Cancel',
    'forgotPwd.send': 'Send link',
    'forgotPwd.success': 'If an account with that email exists, you will receive a reset link shortly.',
    'forgotPwd.close': 'Close',

    // Register
    'register.title': 'Create account',
    'register.subtitle': 'Join Pooly and start creating surveys',
    'register.username': 'Username',
    'register.usernamePlaceholder': 'Choose a username',
    'register.email': 'Email address',
    'register.emailPlaceholder': 'you@email.com',
    'register.password': 'Password',
    'register.confirmPassword': 'Confirm password',
    'register.submit': 'Create account',
    'register.submitting': 'Creating account...',
    'register.hasAccount': 'Already have an account?',
    'register.loginLink': 'Sign in here',
    'register.errorPasswordMatch': 'Passwords do not match',
    'register.errorUserExists': 'This username is already taken. Please try another.',
    'register.errorGeneric': 'Registration failed. Please try again.',
    'register.errorAutoLogin': 'Account created, but auto sign-in failed. Please sign in manually.',

    // Admin Dashboard
    'admin.loading': 'Loading your dashboard...',
    'admin.hello': 'Hello, {{username}}',
    'admin.subtitle': 'Manage your surveys and analyze your community responses.',
    'admin.statTotal': 'Total surveys',
    'admin.statResponses': 'Total responses',
    'admin.statActive': 'Active surveys',
    'admin.statAvg': 'Avg. responses',
    'admin.errorLoad': 'Could not load your events.',
    'admin.errorDemo': 'Showing demo data',
    'admin.deleteSuccess': 'The survey was deleted successfully.',
    'admin.deleteError': 'Could not delete the survey. Please try again.',
    'admin.deleteErrorGeneric': 'Error deleting the survey. Please try again.',
    'admin.sectionTitle': 'My surveys',
    'admin.survey': 'survey',
    'admin.surveys': 'surveys',
    'admin.newSurvey': 'New survey',
    'admin.emptyTitle': 'No surveys yet',
    'admin.emptyDesc': 'Create your first survey to start collecting opinions from your community.',
    'admin.createFirst': 'Create my first survey',
    'admin.tapHint': 'Tap to view details',
    'admin.deleteModalTitle': 'Delete survey',
    'admin.deleteModalMessage': 'Are you sure you want to delete the survey "{{name}}"?',
    'admin.deleteWarning': 'This action cannot be undone. The following will be deleted:',
    'admin.deleteItem1': 'All survey questions',
    'admin.deleteItem2': 'All received responses ({{count}})',
    'admin.deleteItem3': 'All generated analysis reports',
    'admin.cancel': 'Cancel',
    'admin.delete': 'Delete',
    'admin.deleting': 'Deleting...',

    // Event status labels
    'status.ended': 'Ended',
    'status.lastDay': 'Last day',
    'status.closing': 'Closing soon',
    'status.active': 'Active',
    'status.endedDays': 'Ended {{days}} days ago',
    'status.endsToday': 'Ends today',
    'status.daysLeft': '{{days}} days left',

    // Event Details
    'eventDetails.loading': 'Loading event details...',
    'eventDetails.back': '← Back to dashboard',
    'eventDetails.endDate': 'Ends: {{date}}',
    'eventDetails.totalResponses': '{{count}} total responses',
    'eventDetails.analyzeTitle': 'Analyze with AI',
    'eventDetails.analyzing': 'Analyzing...',
    'eventDetails.shareTitle': 'Share link',
    'eventDetails.shareSubtitle': 'Share this link with participants',
    'eventDetails.shareGenerating': 'Generating link...',
    'eventDetails.shareCopy': 'Copy',
    'eventDetails.shareCopied': '✓ Copied',
    'eventDetails.shareHint': 'Responses are completely anonymous. Participants do not need to create an account.',
    'eventDetails.tabResponses': 'Responses',
    'eventDetails.tabReports': 'AI Reports',
    'eventDetails.tabStatus': 'Status',
    'eventDetails.noResponses': 'No responses yet.',
    'eventDetails.responses': 'responses',
    'eventDetails.errorLoad': 'Could not load event details.',

    // Reports tab
    'reports.title': 'Response Analysis',
    'reports.subtitle': '{{count}} categories identified by AI',
    'reports.subtitleEmpty': 'Reports will appear here after analysis',
    'reports.refresh': '↻ Refresh',
    'reports.loading': 'Loading...',
    'reports.loadingState': 'Loading reports...',
    'reports.error': 'Could not load reports.',
    'reports.errorDemo': 'Showing demo data',
    'reports.emptyTitle': 'No reports available',
    'reports.emptyDesc': 'Run an AI analysis to get insights from the responses.',
    'reports.analyzeBtn': 'Analyze with AI',
    'reports.generated': 'Generated: {{date}}',
    'reports.examples': 'Examples:',
    'reports.mentions': 'mentions',
    'reports.ofTotal': 'of total',

    // Sentiment / Urgency
    'sentiment.positive': 'Positive',
    'sentiment.negative': 'Negative',
    'sentiment.neutral': 'Neutral',
    'urgency.high': 'High',
    'urgency.medium': 'Medium',
    'urgency.low': 'Low',
    'urgency.label': 'Urgency: {{level}}',

    // Jobs / Status tab
    'jobs.title': 'Analysis Status',
    'jobs.subtitle': '{{count}} jobs registered',
    'jobs.subtitleEmpty': 'Analysis jobs will appear here',
    'jobs.loading': 'Loading jobs...',
    'jobs.error': 'Unable to retrieve information at this time.',
    'jobs.emptyTitle': 'No jobs registered',
    'jobs.emptyDesc': 'When you start an AI analysis, you can monitor its progress here.',
    'jobs.colId': 'ID',
    'jobs.colStatus': 'Status',
    'jobs.colMessage': 'Message',
    'jobs.colStarted': 'Started',
    'jobs.colUpdated': 'Updated',
    'jobs.statusCompleted': 'Completed',
    'jobs.statusRunning': 'Running',
    'jobs.statusError': 'Error',

    // Analyze modal
    'analyzeModal.title': 'Start AI analysis',
    'analyzeModal.cancel': 'Cancel',
    'analyzeModal.confirm': 'Start analysis',
    'analyzeModal.statusSuccess': 'Analysis started successfully! You can monitor progress in the Status section.',
    'analyzeModal.statusError': 'Error starting analysis. Please try again.',

    // Create Event
    'create.back': '← Back to dashboard',
    'create.title': 'Create new survey',
    'create.step': 'Step {{step}} of 2',
    'create.step1Label': 'Survey details',
    'create.step2Label': 'Add questions',
    'create.name': 'Survey name',
    'create.namePlaceholder': 'e.g. Urban Mobility 2026',
    'create.description': 'Description',
    'create.descPlaceholder': 'Describe the purpose of this survey...',
    'create.endDate': 'End date',
    'create.next': 'Next: Add questions',
    'create.errorNoDate': 'Please select an end date for the survey.',
    'create.errorPastDate': 'The end date must be in the future.',
    'create.questionsLabel': 'Survey questions',
    'create.questionsHint': 'Write open-ended questions so participants can answer freely.',
    'create.questionPlaceholder': 'Write question {{num}}',
    'create.addQuestion': '+ Add another question',
    'create.questionRequired': 'Required',
    'create.questionOptional': 'Optional',
    'create.prev': 'Previous',
    'create.submit': 'Create survey',
    'create.submitting': 'Creating...',
    'create.errorNoQuestions': 'Please add at least one question.',
    'create.errorGeneric': 'Error creating the survey.',
    'tips.step1.title': 'Tips for your survey',
    'tips.step1.tip1.title': 'Clear, specific title',
    'tips.step1.tip1.desc': 'A good title helps participants understand the topic. E.g.: "Urban Mobility 2026" instead of "Survey".',
    'tips.step1.tip2.title': 'Motivating description',
    'tips.step1.tip2.desc': 'Explain why participation matters and how responses will be used to make decisions.',
    'tips.step1.tip3.title': 'Enough time',
    'tips.step1.tip3.desc': 'Allow at least 1-2 weeks for participants to respond at their own pace.',
    'tips.step1.highlight': 'Surveys with clear descriptions get 40% more participation.',
    'tips.step2.title': 'Create effective questions',
    'tips.step2.tip1.title': 'Open-ended questions',
    'tips.step2.tip1.desc': 'They allow detailed responses that our AI can analyze to find patterns and trends.',
    'tips.step2.tip2.title': 'Avoid bias',
    'tips.step2.tip2.desc': "Don't lead responses. \"What do you think of transportation?\" is better than \"Don't you think transportation is bad?\"",
    'tips.step2.tip3.title': 'One idea per question',
    'tips.step2.tip3.desc': "Split complex questions. It's easier to analyze \"What transport do you use?\" and \"What would you improve?\" separately.",
    'tips.step2.highlight': 'Our AI analyzes responses to automatically identify topics, sentiment, and priorities.',
    'tips.examples.title': 'Examples of good questions',
    'tips.examples.item1': 'What is the main problem you face with...?',
    'tips.examples.item2': 'What would you change if you could...?',
    'tips.examples.item3': 'How does it currently affect you...?',

    // Edit Event / Questions
    'editEvent.editBtn': 'Edit Event',
    'editEvent.saveBtn': 'Save',
    'editEvent.cancelBtn': 'Cancel',
    'editEvent.saving': 'Saving...',
    'editEvent.addQuestion': '+ Add question',
    'editEvent.saveSuccess': 'Saved successfully',
    'editEvent.saveError': 'Error saving information',
    'editEvent.newQuestionsLabel': 'New questions',
    'editEvent.existingQuestionsLabel': 'Existing questions',
    'editEvent.questionPlaceholder': 'Write new question {{num}}',

    // Settings
    'settings.back': '← Back to dashboard',
    'settings.title': 'Settings',
    'settings.subtitle': 'Your account details',
    'settings.sectionTitle': 'User information',
    'settings.username': 'Username',
    'settings.email': 'Email address',
    'settings.role': 'Role',
    'settings.roleDefault': 'User',

    // Landing page
    'landing.nav.product': 'Product',
    'landing.nav.how': 'How it works',
    'landing.nav.customers': 'Customers',
    'landing.nav.pricing': 'Pricing',
    'landing.hero.kicker': 'AI-Powered Survey Platform',
    'landing.hero.title1': 'Surveys that think.',
    'landing.hero.title2': 'Answers that matter.',
    'landing.hero.sub': 'Pooly uses AI to help you build smarter surveys, reach the right audience, and turn responses into decisions — faster than ever.',
    'landing.hero.cta1': 'Start for free',
    'landing.hero.cta2': 'See how it works',
    'landing.hero.note': 'No credit card required · Free plan forever',
    'landing.hero.stat1.value': '2,847',
    'landing.hero.stat1.label': 'Responses today',
    'landing.hero.stat1.trend': '↑ 18% this week',
    'landing.hero.stat2.label': 'Completion rate',
    'landing.hero.stat2.trend': '↑ vs. industry avg',
    'landing.f1.eyebrow': 'AI Survey Builder',
    'landing.f1.title': 'Go from idea to live survey in seconds',
    'landing.f1.body': "Describe what you want to learn and Pooly's AI engine drafts a complete, optimized survey — with smart question logic, branching, and bias detection built in.",
    'landing.f1.li1': 'Generate full surveys from a single prompt',
    'landing.f1.li2': 'Auto-detect and fix leading questions',
    'landing.f1.li3': 'Smart skip logic and conditional branching',
    'landing.f1.li4': 'Multilingual support out of the box',
    'landing.f1.cta': 'Build your first survey →',
    'landing.midcta.h3': 'Ready to hear what your customers really think?',
    'landing.midcta.p': 'Join over 50,000 teams already using Pooly to make smarter decisions.',
    'landing.midcta.btn': 'Get started free →',
    'landing.f2.eyebrow': 'Real-time Analytics',
    'landing.f2.title': 'Responses turn into insights automatically',
    'landing.f2.body': "Watch answers come in live. Pooly's AI surfaces trends, sentiment shifts, and key themes as responses roll in — no manual analysis required.",
    'landing.f2.li1': 'Live response dashboard with filters',
    'landing.f2.li2': 'AI-generated summary of open-text responses',
    'landing.f2.li3': 'Exportable reports (CSV, PDF, Notion)',
    'landing.f2.cta': 'See analytics demo →',
    'landing.stats.l1': 'Teams using Pooly',
    'landing.stats.l2': 'Survey responses collected',
    'landing.stats.l3': 'Average completion rate',
    'landing.stats.l4': 'Faster than building manually',
    'landing.f3.eyebrow': 'Template Library',
    'landing.f3.title': '100+ expert-built templates to get you started',
    'landing.f3.body': 'From NPS and CSAT to employee engagement and market research — every template is research-backed and ready to customize.',
    'landing.f3.li1': 'Categorized by industry and use case',
    'landing.f3.li2': 'Fully customizable branding',
    'landing.f3.li3': 'One-click deploy via link, email, or embed',
    'landing.f3.cta': 'Browse templates →',
    'landing.f4.eyebrow': 'Built for teams',
    'landing.f4.title': 'The whole team, on the same page',
    'landing.f4.body': 'Collaborate on surveys, share results with stakeholders, and manage permissions — all in one place. Real people, real workflows.',
    'landing.f4.li1': 'Multi-user workspaces with role-based access',
    'landing.f4.li2': 'Shared results and collaborative annotations',
    'landing.f4.li3': 'SSO, audit logs, and enterprise compliance',
    'landing.f4.cta': 'Explore team features',
    'landing.hiw.eyebrow': 'How it works',
    'landing.hiw.title': 'Three steps to better answers',
    'landing.hiw.body': 'From prompt to published in under two minutes. Pooly handles the hard parts so you can focus on the insights.',
    'landing.hiw.s1.title': 'Describe your goal',
    'landing.hiw.s1.body': 'Tell Pooly what you want to learn — in plain English. No survey design experience needed.',
    'landing.hiw.s2.title': 'Review & customize',
    'landing.hiw.s2.body': 'AI drafts your survey instantly. Edit questions, add your branding, and set up distribution logic.',
    'landing.hiw.s3.title': 'Share & analyze',
    'landing.hiw.s3.body': 'Send via link, email, or embed. Watch insights surface automatically as responses come in.',
    'landing.hiw.cta': 'Try it free →',
    'landing.t.eyebrow': 'Customer stories',
    'landing.t.title': 'Trusted by people who need real answers',
    'landing.t.q1': "Pooly cut our survey setup time in half. The AI suggestions are genuinely good — it caught leading questions we didn't even notice.",
    'landing.t.n1': 'Sara Velázquez',
    'landing.t.r1': 'Head of Research, Meridian',
    'landing.t.q2': 'We ran our first NPS survey within 10 minutes of signing up. The response rate was 40% higher than our previous tool — the design really matters.',
    'landing.t.n2': 'Marcus Chen',
    'landing.t.r2': 'Product Manager, Northvale',
    'landing.t.q3': 'The real-time analytics are incredible. I shared a live dashboard with our board while the survey was still running — they were blown away.',
    'landing.t.n3': 'Aisha Okonkwo',
    'landing.t.r3': 'Director of Strategy, Arkon Labs',
    'landing.p.eyebrow': 'Pricing',
    'landing.p.title': 'Simple, honest pricing',
    'landing.p.body': 'Start free. Upgrade when you need more power. No hidden fees.',
    'landing.p.free.plan': 'Free',
    'landing.p.free.period': 'forever',
    'landing.p.free.desc': 'Perfect for individuals exploring AI-assisted surveys.',
    'landing.p.free.li1': '3 active surveys',
    'landing.p.free.li2': '100 responses / month',
    'landing.p.free.li3': 'AI survey builder',
    'landing.p.free.li4': 'Basic analytics',
    'landing.p.free.btn': 'Get started',
    'landing.p.pro.plan': 'Pro',
    'landing.p.pro.badge': 'Most popular',
    'landing.p.pro.period': 'per month',
    'landing.p.pro.desc': 'For teams that need unlimited surveys and advanced AI.',
    'landing.p.pro.li1': 'Unlimited surveys',
    'landing.p.pro.li2': '10,000 responses / month',
    'landing.p.pro.li3': 'Advanced AI analytics',
    'landing.p.pro.li4': 'Custom branding',
    'landing.p.pro.li5': 'CSV & PDF exports',
    'landing.p.pro.li6': 'Priority support',
    'landing.p.pro.btn': 'Start free trial',
    'landing.p.ent.plan': 'Enterprise',
    'landing.p.ent.price': 'Custom',
    'landing.p.ent.period': 'contact us',
    'landing.p.ent.desc': 'For large organizations with security and compliance requirements.',
    'landing.p.ent.li1': 'Unlimited everything',
    'landing.p.ent.li2': 'SSO & audit logs',
    'landing.p.ent.li3': 'Enterprise compliance',
    'landing.p.ent.li4': 'Dedicated onboarding',
    'landing.p.ent.li5': 'SLA guarantee',
    'landing.p.ent.li6': 'Custom integrations',
    'landing.p.ent.btn': 'Contact sales',
    'landing.cta.title': 'Start making decisions with confidence.',
    'landing.cta.body': 'Join 50,000+ teams who run smarter surveys with Pooly.',
    'landing.cta.btn1': 'Get started free →',
    'landing.cta.btn2': 'Sign in',
    'landing.footer.tagline': 'AI-powered surveys that help teams make better decisions, faster.',
    'landing.footer.col1': 'Product',
    'landing.footer.col2': 'Resources',
    'landing.footer.col3': 'Learn',
    'landing.footer.col4': 'About',
    'landing.footer.p1': 'Survey Builder',
    'landing.footer.p2': 'Analytics',
    'landing.footer.p3': 'Templates',
    'landing.footer.p4': 'Pricing',
    'landing.footer.r1': 'Documentation',
    'landing.footer.r2': 'API Reference',
    'landing.footer.r3': 'Integrations',
    'landing.footer.r4': 'Status',
    'landing.footer.l1': 'Blog',
    'landing.footer.l2': 'Survey Guides',
    'landing.footer.l3': 'Case Studies',
    'landing.footer.l4': 'Webinars',
    'landing.footer.a1': 'Company',
    'landing.footer.a2': 'Careers',
    'landing.footer.a3': 'Press',
    'landing.footer.a4': 'Contact',
    'landing.footer.copy': '© 2025 Pooly. All rights reserved.',
    'landing.footer.privacy': 'Privacy Policy',
    'landing.footer.terms': 'Terms of Service',
    'landing.footer.cookies': 'Cookie Settings',

    // Public Gallery
    'gallery.badge': 'Civic participation platform',
    'gallery.heroTitle1': 'Transform thousands of voices into',
    'gallery.heroTitle2': 'actionable insights',
    'gallery.heroDesc': 'Create surveys, collect opinions from your community, and get automatic AI analysis. Discover patterns, sentiments, and priorities without predefined categories.',
    'gallery.ctaStart': 'Get started free',
    'gallery.ctaLogin': 'I already have an account',
    'gallery.howTitle': 'How it works',
    'gallery.howDesc': 'Three simple steps to turn your community feedback into informed decisions.',
    'gallery.step1Title': 'Create your survey',
    'gallery.step1Desc': 'Define the open-ended questions you want to ask your community. No limits on predefined options.',
    'gallery.step2Title': 'Share the link',
    'gallery.step2Desc': 'Distribute the unique link. Participants respond anonymously from any device.',
    'gallery.step3Title': 'Get insights',
    'gallery.step3Desc': 'Our AI groups responses, identifies emerging topics, and analyzes sentiment automatically.',
    'gallery.aiTitle': 'Powered by artificial intelligence',
    'gallery.aiDesc': 'Advanced Natural Language Processing technology to understand what your community really needs.',
    'gallery.feature1Title': 'Automatic discovery',
    'gallery.feature1Desc': 'Translates thousands of individual voices into clear categories without predefining them. AI finds the patterns for you.',
    'gallery.feature2Title': 'Priority analysis',
    'gallery.feature2Desc': 'Ranks topics by importance, sentiment, and urgency. Make decisions based on real data from your community.',
    'gallery.feature3Title': 'Multilingual',
    'gallery.feature3Desc': 'Support for 50+ languages. Receive responses in any language and get unified, consistent analysis.',
    'gallery.useCasesTitle': 'Use cases',
    'gallery.useCasesDesc': 'From urban planning to market research, Pooly adapts to your needs.',
    'gallery.useCase1Title': 'Urban planning',
    'gallery.useCase1Desc': 'Collect citizen feedback on infrastructure, parks, and public services. Visualize the future of your city through community collaboration.',
    'gallery.useCase2Title': 'Events & conferences',
    'gallery.useCase2Desc': 'Understand attendee satisfaction and gather improvement suggestions. From conferences to festivals, amplify every voice.',
    'gallery.useCase3Title': 'Product research',
    'gallery.useCase3Desc': 'Test new ideas directly with your community and iterate quickly. Insights that drive meaningful innovation.',
    'gallery.statLang': 'Languages supported',
    'gallery.statAi': 'Intelligent analysis',
    'gallery.statAnon': 'Anonymous and secure',
    'gallery.ctaTitle': 'Start listening to your community',
    'gallery.ctaDesc': 'Create your first survey in minutes. No credit card required.',
    'gallery.ctaBtn': 'Create free account',
    'gallery.footer': '© 2025 Pooly. Civic participation platform.',

    // Public Survey
    'survey.loading': 'Loading survey...',
    'survey.notFound': 'Survey not found',
    'survey.notFoundDesc': 'The link you followed is not valid or the survey is no longer available.',
    'survey.goToPooly': 'Go to Pooly',
    'survey.progressBadge': '{{answered}} of {{total}}',
    'survey.question': 'Question {{num}}',
    'survey.placeholder': 'Write your answer here...',
    'survey.anonymous': 'Your responses are anonymous and secure',
    'survey.submit': 'Submit',
    'survey.submitting': 'Submitting...',
    'survey.successTitle': 'Thank you for your participation!',
    'survey.successDesc': 'Your responses have been recorded successfully.',
    'survey.successNote': 'Your opinion is valuable and helps us make better decisions.',
    'survey.errorAtLeastOne': 'Please answer at least one question.',
    'survey.errorMaxChars': 'Answers {{nums}} cannot exceed 500 characters.',
    'survey.errorSubmit': 'Error submitting responses.',
    'survey.errorLoad': 'Could not load the survey.',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem('pooly_language') || 'es'
  );

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('pooly_language', lang);
  };

  const t = (key, vars = {}) => {
    let str = translations[language]?.[key] ?? key;
    Object.entries(vars).forEach(([k, v]) => {
      str = str.replace(new RegExp(`\\{\\{${k}\\}\\}`, 'g'), String(v));
    });
    return str;
  };

  const locale = language === 'es' ? 'es-MX' : 'en-US';

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, locale }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
