import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext(null);

const translations = {
  es: {
    // Navbar
    'navbar.controlPanel': 'Panel de control',
    'navbar.settings': 'Configuración',
    'navbar.login': 'Iniciar sesión',
    'navbar.register': 'Comenzar',
    'navbar.logout': 'Cerrar sesión',
    'lang.es': 'Español',
    'lang.en': 'English',

    // Demo modal
    'demoModal.title': 'Agenda tu demo',
    'demoModal.body': 'Elige un horario nuestro calendario y platicamos cómo Pooly puede ayudar a tu marca.',
    'demoModal.cta': 'Ir a Calendly',

    // Auth - social & legal
    'auth.socialDivider': 'o continúa con',
    'auth.emailDivider': 'o continúa con email',
    'auth.google': 'Continuar con Google',
    'auth.googleError': 'Error al iniciar sesión con Google. Inténtalo de nuevo.',
    'register.legalPrefix': 'Al registrarte, aceptas los',
    'register.termsLink': 'Términos de uso',
    'register.legalAnd': 'y el',
    'register.privacyLink': 'Aviso de privacidad',
    'register.legalSuffix': '. También aceptas recibir novedades del producto y promociones especiales por correo electrónico. Puedes cancelar estos correos en cualquier momento desde tu página de Preferencias de cuenta.',
    'register.notifications': 'Quiero recibir novedades, ofertas y noticias de Pooly.mx',

    // Login
    'login.title': 'Bienvenido de nuevo',
    'login.subtitle': 'Inicia sesión para gestionar tus encuestas',
    'login.email': 'Correo electrónico',
    'login.emailPlaceholder': 'tu@correo.com',
    'login.password': 'Contraseña',
    'login.forgotPassword': '¿Olvidaste tu contraseña?',
    'login.submit': 'Iniciar sesión',
    'login.submitting': 'Iniciando sesión...',
    'login.noAccount': '¿No tienes cuenta?',
    'login.registerLink': 'Regístrate aquí',
    'login.error': 'Error al iniciar sesión. Verifica tus credenciales.',

    // Forgot password
    'forgotPwd.title': 'Recuperar contraseña',
    'forgotPwd.description': 'Ingresa tu correo y te enviaremos un enlace para restablecer tu contraseña.',
    'forgotPwd.email': 'Correo electrónico',
    'forgotPwd.placeholder': 'tu@correo.com',
    'forgotPwd.cancel': 'Cancelar',
    'forgotPwd.send': 'Enviar enlace',
    'forgotPwd.success': 'Si existe una cuenta con ese correo, recibirás un enlace en breve.',
    'forgotPwd.close': 'Cerrar',
    'forgotPwd.error': 'Ocurrió un error. Inténtalo de nuevo.',

    // Reset password page
    'resetPwd.title': 'Nueva contraseña',
    'resetPwd.subtitle': 'Elige una contraseña segura para tu cuenta.',
    'resetPwd.password': 'Nueva contraseña',
    'resetPwd.confirmPassword': 'Confirmar contraseña',
    'resetPwd.submit': 'Guardar contraseña',
    'resetPwd.submitting': 'Guardando...',
    'resetPwd.success': 'Tu contraseña se actualizó. Ya puedes iniciar sesión.',
    'resetPwd.goToLogin': 'Ir a iniciar sesión',
    'resetPwd.errorMatch': 'Las contraseñas no coinciden.',
    'resetPwd.errorLength': 'La contraseña debe tener al menos 8 caracteres.',
    'resetPwd.errorExpired': 'Este link ha expirado. Solicita un nuevo enlace de recuperación.',
    'resetPwd.errorInvalid': 'El link no es válido.',
    'resetPwd.errorGeneric': 'Ocurrió un error. Inténtalo de nuevo.',
    'resetPwd.requestNew': 'Solicitar nuevo enlace',

    // Register
    'register.title': 'Crear cuenta',
    'register.subtitle': 'Únete a Pooly y comienza a crear encuestas',
    'register.name': 'Nombre',
    'register.namePlaceholder': 'Tu nombre',
    'register.email': 'Correo electrónico',
    'register.emailPlaceholder': 'tu@correo.com',
    'register.password': 'Contraseña',
    'register.confirmPassword': 'Confirmar contraseña',
    'register.submit': 'Crear cuenta',
    'register.submitting': 'Creando cuenta...',
    'register.hasAccount': '¿Ya tienes cuenta?',
    'register.loginLink': 'Inicia sesión aquí',
    'register.errorPasswordLength': 'La contraseña debe tener al menos 8 caracteres.',
    'register.errorPasswordMatch': 'Las contraseñas no coinciden',
    'register.errorUserExists': 'Este usuario ya existe. Intenta con otro nombre de usuario.',
    'register.errorGeneric': 'Error en el registro. Inténtalo de nuevo.',
    'register.errorAutoLogin': 'Cuenta creada, pero el inicio de sesión automático falló. Por favor inicia sesión manualmente.',
    'register.errorEmailExists': 'Este correo ya está registrado. ¿Olvidaste tu contraseña?',
    'register.send_verification': 'Enviar link de verificación',
    'register.send_verification_submitting': 'Enviando...',
    'register.check_email': 'Te enviamos un link de verificación. Revisa tu bandeja de entrada y haz clic en el enlace para continuar. El link expira en 30 minutos.',
    'register.check_email_sent_to': 'Te enviamos un link de verificación a {{email}}.',
    'register.token_verifying': 'Verificando enlace...',
    'register.token_expired': 'Este link ha expirado. Solicita uno nuevo.',
    'register.token_invalid': 'El link no es válido o ya fue utilizado.',
    'register.verified_email_label': 'Correo verificado',
    'register.request_new_link': 'Solicitar nuevo link',
    'register.complete_title': 'Completa tu registro',

    // Admin Dashboard
    'admin.loading': 'Cargando tu panel de control...',
    'admin.hello': 'Hola, {{username}}',
    'admin.subtitle': 'Esto es lo que tus clientes están diciendo hoy.',
    'admin.statTotal': 'Encuestas',
    'admin.statResponses': 'Respuestas',
    'admin.statActive': 'Activas',
    'admin.statAvg': 'Prom. respuestas',
    'admin.errorLoad': 'No se pudieron cargar tus eventos.',
    'admin.errorDemo': 'Mostrando datos de demostración',
    'admin.deleteSuccess': 'La encuesta se eliminó correctamente.',
    'admin.deleteError': 'No se pudo eliminar la encuesta. Intenta de nuevo.',
    'admin.deleteErrorGeneric': 'Error al eliminar la encuesta. Intenta de nuevo.',
    'admin.sectionTitle': 'Tus encuestas',
    'admin.survey': 'encuesta',
    'admin.surveys': 'encuestas',
    'admin.project': 'proyecto',
    'admin.projects': 'proyectos',
    'admin.newSurvey': 'Nueva encuesta',
    'admin.importResults': 'Importar resultados',
    'admin.suggestedAction': 'Acción sugerida',
    'admin.viewTopic': 'Ver tema',
    'admin.viewInsights': 'Ver insights',
    'admin.entryCreateTitle': 'Nueva Encuesta',
    'admin.entryCreateDesc': 'Crea y comparte una encuesta en línea desde Pooly.',
    'admin.entryImportTitle': 'Importar Resultados',
    'admin.entryImportDesc': 'Sube respuestas en desde un archivo Excel o CSV',
    'admin.importedFrom': 'Importado desde {{source}}',
    'admin.emptyTitle': 'Aún no tienes proyectos',
    'admin.emptyDesc': 'Crea una nueva encuesta o importa resultados existentes para obtener análisis con IA.',
    'admin.createFirst': 'Crear mi primera encuesta',
    'admin.tapHint': 'Toca para ver detalles',
    'admin.deleteModalTitle': 'Eliminar encuesta',
    'admin.deleteModalMessage': '¿Estás seguro de que deseas eliminar la encuesta "{{name}}"?',
    'admin.deleteWarning': 'Esta acción no se puede deshacer. Se eliminarán:',
    'admin.deleteItem1': 'Todas las preguntas de la encuesta',
    'admin.deleteItem2': 'Todas las respuestas recibidas ({{count}})',
    'admin.deleteItem3': 'Todos los reportes de análisis generados',
    'admin.cancel': 'Cancelar',
    'admin.delete': 'Eliminar',
    'admin.deleting': 'Eliminando...',
    'admin.edit': 'Editar',
    'admin.duplicate': 'Duplicar',
    'admin.pause': 'Pausar',
    'admin.resume': 'Reanudar',
    'admin.paused': 'Pausada',
    'admin.duplicateSuccess': 'Encuesta duplicada exitosamente.',
    'admin.duplicateError': 'No se pudo duplicar la encuesta. Intenta de nuevo.',
    'admin.pauseSuccess': 'Encuesta pausada.',
    'admin.resumeSuccess': 'Encuesta reanudada.',
    'admin.pauseError': 'No se pudo cambiar el estado. Intenta de nuevo.',

    // Event status labels
    'status.ended': 'Finalizada',
    'status.lastDay': 'Último día',
    'status.closing': 'Por cerrar',
    'status.active': 'Activa',
    'status.endedDays': 'Terminó hace {{days}} días',
    'status.endsToday': 'Termina hoy',
    'status.daysLeft': '{{days}} días restantes',
    'status.alwaysOpen': 'Siempre abierta',
    'status.alwaysOpenText': 'Sin fecha de cierre',

    // Event Details
    'eventDetails.loading': 'Cargando detalles del evento...',
    'eventDetails.back': '← Volver al panel',
    'eventDetails.refresh': 'Actualizar respuestas',
    'eventDetails.endDate': 'Finaliza: {{date}}',
    'eventDetails.totalResponses': '{{count}} respuestas totales',
    'eventDetails.analyzeTitle': 'Analizar con IA',
    'eventDetails.analyzing': 'Analizando...',
    'eventDetails.shareTitle': 'Enlace para compartir',
    'eventDetails.shareSubtitle': 'Comparte este enlace con tus clientes',
    'eventDetails.shareGenerating': 'Generando enlace...',
    'eventDetails.shareCopy': 'Copiar',
    'eventDetails.shareCopied': '✓ Copiado',
    'eventDetails.shareHint': 'Las respuestas son completamente anónimas. Tus clientes no necesitan crear cuenta.',
    'eventDetails.importTitle': 'Origen de los datos',
    'eventDetails.importSubtitle': 'Este proyecto usa respuestas importadas y converge al mismo análisis de IA.',
    'eventDetails.importSource': 'Fuente',
    'eventDetails.importFile': 'Archivo',
    'eventDetails.importRows': 'Respuestas importadas',
    'eventDetails.importDate': 'Fecha de carga',
    'eventDetails.importSourceFallback': 'Carga manual',
    'eventDetails.importFileFallback': 'Archivo no disponible',
    'eventDetails.importDateFallback': 'Sin registrar',
    'eventDetails.importNoPreview': 'No hay vista previa de respuestas todavía. Una vez que el backend procese el archivo, aquí aparecerán agrupadas por pregunta o columna.',
    'eventDetails.tabOverview': 'Recomendaciones',
    'eventDetails.tabInsights': 'Análisis de categorías',
    'eventDetails.tabTrends': 'Tendencias',
    'eventDetails.tabResponses': 'Respuestas',
    'eventDetails.tabReports': 'Reportes IA',
    'eventDetails.tabCharts': 'Gráficos',
    'eventDetails.tabStatus': 'Status',
    'eventDetails.noResponses': 'Sin respuestas aún.',
    'eventDetails.responses': 'respuestas',
    'eventDetails.errorLoad': 'No se pudieron cargar los detalles del evento.',

    // Reports tab
    'reports.title': 'Análisis de Respuestas',
    'reports.subtitle': '{{count}} categorías identificadas por IA',
    'reports.subtitleEmpty': 'Los reportes aparecerán aquí después del análisis',
    'reports.refresh': '↻ Actualizar',
    'reports.loading': 'Cargando...',
    'reports.loadingState': 'Cargando reportes...',
    'reports.error': 'No se pudieron cargar los reportes.',
    'reports.errorDemo': 'Mostrando datos de demostración',
    'reports.emptyTitle': 'Sin reportes disponibles',
    'reports.emptyDesc': 'Genera un análisis con IA para obtener insights de las respuestas.',
    'reports.analyzeBtn': 'Analizar con IA',
    'reports.generated': 'Generado: {{date}}',
    'reports.examples': 'Ejemplos:',
    'reports.mentions': 'menciones',
    'reports.ofTotal': 'del total',

    // Charts tab
    'charts.title': 'Gráficos de Tendencias',
    'charts.barTitle': 'Top problemas detectados',
    'charts.pieTitle': 'Distribución del sentimiento',
    'charts.percentage': 'Porcentaje',
    'charts.noData': 'Sin datos para graficar. Genera un análisis con IA primero.',
    'charts.exportBtn': 'Exportar PDF',
    'charts.exportingBtn': 'Generando...',

    // Sentiment / Urgency
    'sentiment.positive': 'Positivo',
    'sentiment.negative': 'Negativo',
    'sentiment.neutral': 'Neutral',
    'urgency.high': 'Alta',
    'urgency.medium': 'Media',
    'urgency.low': 'Baja',
    'urgency.label': 'Urgencia: {{level}}',

    // Jobs / Status tab
    'jobs.title': 'Estado de Análisis',
    'jobs.subtitle': '{{count}} trabajos registrados',
    'jobs.subtitleEmpty': 'Los trabajos de análisis aparecerán aquí',
    'jobs.loading': 'Cargando trabajos...',
    'jobs.error': 'No es posible recuperar la información en este momento.',
    'jobs.emptyTitle': 'Sin trabajos registrados',
    'jobs.emptyDesc': 'Cuando inicies un análisis con IA, podrás ver su progreso aquí.',
    'jobs.colId': 'ID',
    'jobs.colStatus': 'Estado',
    'jobs.colMessage': 'Mensaje',
    'jobs.colStarted': 'Iniciado',
    'jobs.colUpdated': 'Finalizado',
    'jobs.statusCompleted': 'Completado',
    'jobs.statusRunning': 'En proceso',
    'jobs.statusError': 'Error',

    // Analyze modal
    'analyzeModal.title': 'Iniciar análisis con IA',
    'analyzeModal.cancel': 'Cancelar',
    'analyzeModal.confirm': 'Iniciar análisis',
    'analyzeModal.statusSuccess': '¡Análisis iniciado exitosamente! Puedes monitorear el progreso en la sección Status.',
    'analyzeModal.statusError': 'Error al iniciar el análisis. Intenta de nuevo.',

    // Create Event
    'create.back': '← Volver al panel',
    'create.title': 'Crear nueva encuesta',
    'create.step': 'Paso {{step}} de 2',
    'create.step1Label': 'Detalles de la encuesta',
    'create.step2Label': 'Agregar preguntas',
    'create.name': 'Nombre de la encuesta',
    'create.namePlaceholder': 'ej. Feedback post-compra Q3 2026',
    'create.description': 'Descripción',
    'create.descPlaceholder': 'Describe el propósito de esta encuesta...',
    'create.endDate': 'Fecha de cierre',
    'create.endDateToggle': 'Definir fecha de cierre',
    'create.next': 'Siguiente: Agregar preguntas',
    'create.errorNoDate': 'Por favor selecciona una fecha de cierre para la encuesta.',
    'create.errorPastDate': 'La fecha de cierre debe ser una fecha futura.',
    'create.questionsLabel': 'Preguntas de la encuesta',
    'create.questionsHint': 'Escribe tus preguntas y define el tipo de respuesta esperada.',
    'create.questionPlaceholder': 'Escribe la pregunta {{num}}',
    'create.questionTypeOpen': 'Texto libre',
    'create.questionTypeMultiple': 'Opción múltiple',
    'create.questionTypeNumeric': 'Numérico',
    'create.questionTypeDate': 'Fecha',
    'create.addQuestion': '+ Agregar otra pregunta',
    'create.questionRequired': 'Obligatoria',
    'create.questionOptional': 'Opcional',
    'create.optionPlaceholder': 'Opción {{num}}',
    'create.addOption': '+ Agregar opción',
    'create.prev': 'Anterior',
    'create.preview': 'Vista previa',
    'create.submit': 'Crear encuesta',
    'create.submitting': 'Creando...',
    'create.errorNoQuestions': 'Por favor agrega al menos una pregunta.',
    'create.errorMultipleOptions': 'Las preguntas de opción múltiple necesitan al menos 2 opciones.',
    'create.errorGeneric': 'Error al crear la encuesta.',
    'create.successToast': '¡Encuesta creada exitosamente!',
    'create.draftRestoredBanner': 'Recuperamos un borrador que no terminaste. Puedes seguir desde donde lo dejaste.',
    'create.draftDiscard': 'Descartar borrador',
    'create.draftSaved': 'Borrador guardado',
    'tips.step1.title': 'Consejos para tu encuesta',
    'tips.step1.tip1.title': 'Título claro y específico',
    'tips.step1.tip1.desc': 'Un buen título le dice a tu cliente de qué se trata. Ej: "Cuéntanos de tu compra" en lugar de "Encuesta".',
    'tips.step1.tip2.title': 'Descripción motivadora',
    'tips.step1.tip2.desc': 'Dile a tu cliente que su opinión define decisiones reales: qué productos mejorar, cómo mejorar la entrega, qué cambiar.',
    'tips.step1.tip3.title': 'El momento correcto',
    'tips.step1.tip3.desc': 'Envíala cuando la experiencia esté fresca: justo después de la entrega, del soporte o de la devolución.',
    'tips.step1.highlight': 'Las encuestas con descripciones claras tienen 40% más participación.',
    'tips.step2.title': 'Crea preguntas efectivas',
    'tips.step2.tip1.title': 'Preguntas abiertas',
    'tips.step2.tip1.desc': 'Permiten respuestas detalladas que nuestra IA puede analizar para encontrar patrones y tendencias.',
    'tips.step2.tip2.title': 'Evita sesgos',
    'tips.step2.tip2.desc': 'No induzcas respuestas. "¿Qué te pareció el envío?" es mejor que "¿No crees que el envío fue lento?"',
    'tips.step2.tip3.title': 'Elige el tipo correcto',
    'tips.step2.tip3.desc': 'Texto libre para opiniones, Opción múltiple para categorías fijas, Numérico para mediciones como edades o puntajes, y Fecha para eventos.',
    'tips.step2.highlight': 'Nuestra IA analiza las respuestas para identificar temas, sentimiento y prioridades automáticamente.',
    'tips.examples.title': 'Ejemplos de buenas preguntas',
    'tips.examples.item1': '¿Qué te hizo dudar antes de comprar?',
    'tips.examples.item2': '¿Qué mejorarías del producto o de la entrega?',
    'tips.examples.item3': '¿Por qué decidiste devolver tu pedido?',

    // Edit Event / Questions
    'editEvent.editBtn': 'Editar Evento',
    'editEvent.saveBtn': 'Guardar cambios',
    'editEvent.cancelBtn': 'Cancelar',
    'editEvent.saving': 'Guardando...',
    'editEvent.addQuestion': 'Agregar pregunta',
    'editEvent.saveSuccess': 'Cambios guardados exitosamente.',
    'editEvent.saveError': 'Error al guardar la información.',
    'editEvent.newQuestionsLabel': 'Nuevas preguntas',
    'editEvent.existingQuestionsLabel': 'Preguntas existentes',
    'editEvent.questionPlaceholder': 'Escribe la nueva pregunta {{num}}',
    'editEvent.pageTitle': 'Editar encuesta',
    'editEvent.back': '← Volver',
    'editEvent.sectionInfo': 'Información general',
    'editEvent.sectionQuestions': 'Preguntas',
    'editEvent.name': 'Nombre de la encuesta',
    'editEvent.description': 'Descripción',
    'editEvent.endDate': 'Fecha de cierre',
    'editEvent.noEndDate': 'Sin fecha de cierre',
    'editEvent.welcomeLabel': 'Pantalla de bienvenida',
    'editEvent.completionLabel': 'Pantalla de gracias',
    'editEvent.welcomePlaceholder': 'Mensaje de bienvenida (Markdown)',
    'editEvent.completionPlaceholder': 'Mensaje de cierre (Markdown)',
    'editEvent.deleteQuestion': 'Eliminar pregunta',
    'editEvent.backendNote': 'Algunos cambios requieren actualización en el backend.',

    // Settings
    'settings.back': '← Volver al panel',
    'settings.title': 'Configuración',
    'settings.subtitle': 'Detalles de tu cuenta',
    'settings.sectionTitle': 'Información de usuario',
    'settings.username': 'Nombre de usuario',
    'settings.email': 'Correo electrónico',
    'settings.role': 'Rol',
    'settings.roleDefault': 'Usuario',
    'settings.notificationsSection': 'Notificaciones por correo',
    'settings.notificationsLabel': 'Recibir novedades y ofertas de Pooly.mx',
    'settings.notificationsDesc': 'Te enviaremos actualizaciones del producto, novedades y ofertas especiales.',
    'settings.notificationsSaved': 'Preferencia guardada.',
    'settings.notificationsError': 'Error al guardar. Intenta de nuevo.',

    // Landing page
    'landing.nav.how': 'Cómo funciona',
    'landing.nav.pricing': 'Precios',
    'landing.nav.faq': 'Preguntas frecuentes',
    'landing.nav.demoBtn': 'Agendar demo',
    'landing.hero.title1': 'Escucha lo que tus clientes realmente piensan —',
    'landing.hero.title2': 'sin leer cada respuesta.',
    'landing.hero.sub': 'Pooly analiza el feedback abierto de tus clientes con IA y te da temas, sentimiento y recomendaciones de acción en menos de 5 minutos.',
    'landing.hero.cta': 'Agendar tu demo gratis',
    'landing.hero.note': 'Solo para early adopters — acceso desde $19 USD/mes',
    'landing.problem.eyebrow': 'El problema',
    'landing.problem.title': '¿Te suena familiar?',
    'landing.problem.subtitle': 'Sin importar si tienes una tienda en línea o un local físico, el problema es el mismo.',
    'landing.problem.physical.label': 'Negocio físico',
    'landing.problem.physical.p1.title': 'No sabes si la experiencia es consistente',
    'landing.problem.physical.p1.body': 'Tu cliente del local 3 vive algo distinto al del local 1 — y lo descubres cuando ya es tarde.',
    'landing.problem.physical.p2.title': 'El cliente no te dice nada en el momento',
    'landing.problem.physical.p2.body': 'Sonríe en caja, pero no regresa. Y tú no sabes por qué.',
    'landing.problem.physical.p3.title': 'Tus reviews son 4 estrellas y no entiendes por qué no son 5',
    'landing.problem.physical.p3.body': 'Los comentarios llegan dispersos y nadie los analiza en serio.',
    'landing.problem.ecommerce.label': 'E-commerce',
    'landing.problem.ecommerce.p1.title': 'Carritos abandonados sin explicación',
    'landing.problem.ecommerce.p1.body': 'Tu cliente llegó, vio, y se fue — sin decirte nada. Nadie te explica por qué.',
    'landing.problem.ecommerce.p2.title': 'Reseñas que no dicen nada útil',
    'landing.problem.ecommerce.p2.body': '3 estrellas que solo dicen “ok” o 5 estrellas con “llegó rápido”. Sin información real.',
    'landing.problem.ecommerce.p3.title': 'Horas leyendo soporte sin ver el patrón',
    'landing.problem.ecommerce.p3.body': 'Tickets, mensajes, DMs — y aún no sabes cuál es el problema que más se repite.',
    'landing.fit.eyebrow': '¿Es para ti?',
    'landing.fit.title': 'Veamos en 30 segundos',
    'landing.fit.subtitle': 'Pooly sirve para dos tipos de negocio.',
    'landing.fit.col1.title': 'Sí, si tienes presencia física',
    'landing.fit.col1.subtitle': 'Gimnasio, restaurante, spa, clínica, retail...',
    'landing.fit.col1.li1': 'Tienes clientes que visitan tu negocio y quieres saber qué piensan sin esperar a que dejen una reseña',
    'landing.fit.col1.li2': 'Operas en más de un punto y la consistencia de experiencia te quita el sueño',
    'landing.fit.col1.li3': 'Tus clientes son recurrentes y el churn silencioso es tu mayor amenaza',
    'landing.fit.col1.li4': 'Tomas decisiones de operación y quieres datos, no solo intuición',
    'landing.fit.col2.title': 'Sí, si vendes en línea',
    'landing.fit.col2.subtitle': 'Shopify, WooCommerce, Mercado Libre, VTEX...',
    'landing.fit.col2.li1': 'Recibes feedback de clientes pero leerlo todo tomaría un día entero',
    'landing.fit.col2.li2': 'Quieres saber qué hace que un cliente compre por primera vez — y qué lo hace volver',
    'landing.fit.col2.li3': 'Tus reseñas y tickets de soporte tienen información valiosa que nadie está usando',
    'landing.fit.col2.li4': 'Buscas mejorar conversión y retención con datos reales, no suposiciones',
    'landing.hiw.eyebrow': 'Cómo funciona',
    'landing.hiw.title': 'Así funciona Pooly',
    'landing.hiw.s1.title': 'Crea tu encuesta en 2 minutos',
    'landing.hiw.s1.body': 'Sin configuración técnica. Elige el momento: post-compra, post-entrega, devoluciones o soporte.',
    'landing.hiw.s2.title': 'Tu cliente responde desde el móvil',
    'landing.hiw.s2.body': 'Sin crear cuenta, en segundos, desde el link que tú le mandas.',
    'landing.hiw.s3.title': 'Pooly analiza todo automáticamente',
    'landing.hiw.s3.body': 'Temas emergentes, sentimiento, urgencia y recomendaciones de acción concretas.',
    'landing.platforms.eyebrow': 'Compatibilidad',
    'landing.platforms.title': 'Para marcas que venden en:',
    'landing.platforms.other': '…y cualquier otra plataforma',
    'landing.platforms.body': 'Si tienes una tienda online y quieres entender a tus clientes sin necesitar un equipo de analytics — Pooly es para ti.',
    'landing.pricing.eyebrow': 'Precio',
    'landing.pricing.title': 'Acceso Early Adopter',
    'landing.pricing.priceSuffix': 'USD / mes',
    'landing.pricing.note': 'Precio bloqueado de por vida',
    'landing.pricing.li1': 'Encuestas ilimitadas',
    'landing.pricing.li2': 'Análisis con IA (temas, sentimiento, urgencia)',
    'landing.pricing.li3': 'Recomendaciones de acción automáticas',
    'landing.pricing.li4': 'Soporte directo con el equipo de Pooly',
    'landing.pricing.spots': 'Solo quedan {{n}} de 20 lugares disponibles',
    'landing.pricing.btn': 'Quiero mi acceso early',
    'landing.faq.eyebrow': 'FAQ',
    'landing.faq.title': 'Preguntas frecuentes',
    'landing.faq.q1': '¿Funciona con Shopify / Mercado Libre / VTEX / WooCommerce?',
    'landing.faq.a1': 'Sí. Pooly funciona con cualquier plataforma — no requiere integración técnica. Tú creas la encuesta en Pooly y compartes el link con tus clientes por el canal que prefieras: email, WhatsApp, redes sociales o post-compra.',
    'landing.faq.q2': '¿Mis clientes tienen que crear una cuenta para responder?',
    'landing.faq.a2': 'No. Tu cliente abre el link, responde en texto libre y listo — sin registro, sin apps, desde su teléfono en menos de un minuto.',
    'landing.faq.q3': '¿Cuánto tiempo toma configurar la primera encuesta?',
    'landing.faq.a3': 'Menos de 2 minutos. Eliges el tipo de encuesta (post-compra, devoluciones, soporte), personalizas las preguntas si quieres, y obtienes el link para compartir.',
    'landing.faq.q4': '¿Qué pasa con los datos de mis clientes?',
    'landing.faq.a4': 'Los datos de tus clientes son tuyos. Pooly procesa las respuestas con IA para generar el análisis, pero no los usa para entrenar modelos ni los comparte con terceros.',
    'landing.faq.q5': '¿En qué se diferencia de Typeform o Google Forms?',
    'landing.faq.a5': 'Typeform y Google Forms recolectan respuestas — tú tienes que leerlas y analizarlas. Pooly cierra el loop: analiza automáticamente, identifica patrones y te dice qué hacer. La diferencia es entre tener datos y tener decisiones.',
    'landing.finalcta.title': '¿Tienes 20 minutos?',
    'landing.finalcta.body': 'Te mostramos cómo funciona Pooly con datos reales de tu tienda.',
    'landing.finalcta.btn': 'Agendar demo gratuita',
    'landing.footer.tagline': 'Voz del cliente para e-commerce. De respuestas abiertas a decisiones, en minutos.',
    'landing.footer.login': 'Iniciar sesión',
    'landing.footer.copy': '© 2026 Pooly · Todos los derechos reservados.',
    'landing.footer.privacy': 'Política de privacidad',
    'landing.footer.terms': 'Términos de uso',

    // Public Gallery
    'gallery.badge': 'Voz del cliente para e-commerce',
    'gallery.heroTitle1': 'Convierte las voces de tus clientes en',
    'gallery.heroTitle2': 'insights accionables',
    'gallery.heroDesc': 'Pregúntale a tus clientes con preguntas abiertas y obtén análisis automático con IA en menos de 5 minutos. Temas, sentimiento, urgencia y recomendaciones — sin leer cada respuesta.',
    'gallery.ctaStart': 'Comenzar gratis',
    'gallery.ctaLogin': 'Ya tengo cuenta',
    'gallery.howTitle': 'Cómo funciona',
    'gallery.howDesc': 'Tres pasos simples para convertir el feedback de tus clientes en decisiones de negocio.',
    'gallery.step1Title': 'Crea tu encuesta',
    'gallery.step1Desc': 'Define las preguntas abiertas que quieres hacer a tus clientes: post-compra, post-entrega, devoluciones o validación de producto.',
    'gallery.step2Title': 'Comparte el enlace',
    'gallery.step2Desc': 'Distribuye el enlace por email, WhatsApp o QR. Tus clientes responden en segundos desde el celular, sin crear cuenta.',
    'gallery.step3Title': 'Obtén insights',
    'gallery.step3Desc': 'Nuestra IA agrupa respuestas, identifica temas emergentes y analiza el sentimiento automáticamente.',
    'gallery.aiTitle': 'Potenciado por inteligencia artificial',
    'gallery.aiDesc': 'Tecnología avanzada de Procesamiento de Lenguaje para entender lo que tus clientes realmente piensan.',
    'gallery.feature1Title': 'Descubrimiento automático',
    'gallery.feature1Desc': 'Traduce cientos de respuestas individuales en categorías claras sin necesidad de definirlas previamente. La IA encuentra los patrones por ti.',
    'gallery.feature2Title': 'Análisis de prioridades',
    'gallery.feature2Desc': 'Clasifica los temas por importancia, sentimiento y urgencia. Decide sobre producto, envíos y retención con datos reales de tus clientes.',
    'gallery.feature3Title': 'Multilingüe',
    'gallery.feature3Desc': 'Soporte para más de 50 idiomas. Recibe respuestas en cualquier idioma y obtén análisis unificados y coherentes.',
    'gallery.useCasesTitle': 'Casos de uso',
    'gallery.useCasesDesc': 'Cada momento del journey de tu cliente es una oportunidad para escuchar.',
    'gallery.useCase1Title': 'Encuesta post-compra',
    'gallery.useCase1Desc': 'Entiende qué hizo dudar a tus compradores antes de pagar y qué los convenció. Optimiza tu conversión con las palabras de tus propios clientes.',
    'gallery.useCase2Title': 'Devoluciones y cancelaciones',
    'gallery.useCase2Desc': 'Descubre por qué tus clientes devuelven pedidos o cancelan suscripciones, en sus propias palabras. Reduce el churn atacando la causa real.',
    'gallery.useCase3Title': 'Validación de producto',
    'gallery.useCase3Desc': 'Prueba nuevas ideas y productos directamente con tus clientes e itera rápido. Insights que impulsan tu catálogo.',
    'gallery.statLang': 'Idiomas soportados',
    'gallery.statAi': 'Análisis inteligente',
    'gallery.statAnon': 'Anónimo y seguro',
    'gallery.ctaTitle': 'Empieza a escuchar a tus clientes',
    'gallery.ctaDesc': 'Crea tu primera encuesta en minutos. Sin tarjeta de crédito requerida.',
    'gallery.ctaBtn': 'Crear cuenta gratis',
    'gallery.footer': '© 2026 Pooly. La voz de tus clientes, convertida en decisiones.',

    // Public Survey
    'survey.loading': 'Cargando encuesta...',
    'survey.notFound': 'Encuesta no encontrada',
    'survey.notFoundDesc': 'El enlace que seguiste no es válido o la encuesta ya no está disponible.',
    'survey.pausedTitle': 'Encuesta no disponible',
    'survey.pausedDesc': 'Esta encuesta está temporalmente pausada. Intenta de nuevo más tarde.',
    'survey.previewBanner': 'MODO VISTA PREVIA',
    'survey.previewBannerDesc': 'Esta encuesta no ha sido publicada. Las respuestas no se guardarán.',
    'survey.previewClose': 'Cerrar vista previa',
    'survey.previewSubmitDisabled': 'Envío deshabilitado en vista previa',
    'survey.goToPooly': 'Ir a Pooly',
    'survey.progressBadge': '{{answered}} de {{total}}',
    'survey.question': 'Pregunta {{num}}',
    'survey.placeholder': 'Escribe tu respuesta aquí...',
    'survey.anonymous': 'Tus respuestas son anónimas y seguras',
    'survey.submit': 'Enviar',
    'survey.submitting': 'Enviando...',
    'survey.successTitle': '¡Gracias por tu opinión!',
    'survey.successDesc': 'Tus respuestas se registraron correctamente.',
    'survey.successNote': 'Lo que nos contaste ayuda a la marca a tomar mejores decisiones para ti.',
    'survey.errorAtLeastOne': 'Por favor responde al menos una pregunta.',
    'survey.errorMaxChars': 'Las respuestas {{nums}} no pueden superar los 500 caracteres.',
    'survey.errorSubmit': 'Error al enviar las respuestas.',
    'survey.placeholderNumeric': 'ej. 25',
    'survey.placeholderDate': 'Selecciona una fecha',
    'survey.errorLoad': 'No se pudo cargar la encuesta.',
    'survey.welcomeStart': 'Comenzar encuesta',
    'survey.stepCounter': '{{step}}/{{total}}',
    'survey.introCta': 'Empezar — toma {{min}} min',
    'survey.introDefaultDesc': 'Son {{count}} preguntas rápidas y anónimas. Tu opinión nos ayuda a decidir qué mejorar de verdad.',
    'survey.trustAnonymous': 'Anónimo',
    'survey.trustNoAccount': 'Sin crear cuenta',
    'survey.next': 'Siguiente',
    'survey.continueBlock': 'Continuar',
    'survey.poweredBy': 'Powered by',
    'source.online': 'En línea',
    'source.imported': 'Importado',
    'import.back': '← Volver al panel',
    'import.title': 'Importar resultados',
    'import.subtitle': 'Trae respuestas ya recolectadas en Excel y usa el mismo motor de análisis de Pooly sin recrear tu encuesta.',
    'import.name': 'Nombre del proyecto',
    'import.namePlaceholder': 'ej. Reviews de producto Q2 2026',
    'import.description': 'Descripción',
    'import.descriptionPlaceholder': 'Explica qué contiene este archivo y qué decisión quieres informar.',
    'import.fileLabel': 'Archivo de respuestas',
    'import.fileTitle': 'Selecciona tu archivo',
    'import.fileHelp': 'Arrastra aquí tu archivo o selecciónalo desde tu equipo. Formatos soportados: .xlsx, .xls, .csv — encabezados en la primera fila.',
    'import.fileBrowse': 'Buscar archivo',
    'import.fileEmpty': 'Ningún archivo seleccionado',
    'import.cancel': 'Cancelar',
    'import.submit': 'Importar y continuar',
    'import.submitting': 'Importando...',
    'import.sidebarTitle': 'Cómo preparar tu archivo',
    'import.tip1Title': 'Una fila por respuesta',
    'import.tip1Desc': 'Cada fila debe representar una respuesta individual o un envío completo.',
    'import.tip2Title': 'Texto libre primero',
    'import.tip2Desc': 'El análisis de Pooly funciona mejor con columnas de respuestas abiertas, comentarios u observaciones.',
    'import.tip3Title': 'Mantén el formato simple',
    'import.tip3Desc': 'Evita múltiples hojas, celdas combinadas o encabezados decorativos en el MVP.',
    'import.expectedTitle': 'Formato esperado',
    'import.expected1': 'Primera fila con encabezados claros por columna.',
    'import.expected2': 'Una sola hoja por archivo.',
    'import.expected3': 'Columnas de texto libre para que el modelo identifique temas y sentimiento.',
    'import.highlight': 'Después de la carga, el proyecto entra al mismo flujo de reportes, gráficas y exportación PDF que una encuesta creada dentro de Pooly.',
    'import.errorNoFile': 'Selecciona un archivo para continuar.',
    'import.errorInvalidFile': 'Formato no soportado. Usa .xlsx, .xls o .csv.',
    'import.errorNoColumns': 'Agrega al menos una columna antes de importar.',
    'import.errorSubmit': 'No se pudo importar el archivo. Verifica el formato esperado e intenta de nuevo.',
    'import.errorMissingProject': 'La importación terminó sin devolver un proyecto válido.',
  },

  en: {
    // Navbar
    'navbar.controlPanel': 'Control Panel',
    'navbar.settings': 'Settings',
    'navbar.login': 'Log in',
    'navbar.register': 'Get started',
    'navbar.logout': 'Log out',
    'lang.es': 'Español',
    'lang.en': 'English',

    // Demo modal
    'demoModal.title': 'Book your demo',
    'demoModal.body': "Pick a time on our calendar and we'll show you how Pooly can help your brand.",
    'demoModal.cta': 'Go to Calendly',

    // Auth - social & legal
    'auth.socialDivider': 'or continue with',
    'auth.emailDivider': 'or continue with email',
    'auth.google': 'Continue with Google',
    'auth.googleError': 'Failed to sign in with Google. Please try again.',
    'register.legalPrefix': 'By signing up, you agree to the',
    'register.termsLink': 'Terms of Use',
    'register.legalAnd': 'and',
    'register.privacyLink': 'Privacy Notice',
    'register.legalSuffix': '. You also agree to receive product news and special promotions via email. You can opt-out of these emails in your My Account Preferences page anytime.',
    'register.notifications': 'I want to receive news, offers and updates from Pooly.mx',

    // Login
    'login.title': 'Welcome back',
    'login.subtitle': 'Sign in to manage your surveys',
    'login.email': 'Email address',
    'login.emailPlaceholder': 'you@email.com',
    'login.password': 'Password',
    'login.forgotPassword': 'Forgot your password?',
    'login.submit': 'Sign in',
    'login.submitting': 'Signing in...',
    'login.noAccount': "Don't have an account?",
    'login.registerLink': 'Sign up here',
    'login.error': 'Login failed. Please check your credentials.',

    // Forgot password
    'forgotPwd.title': 'Reset password',
    'forgotPwd.description': 'Enter your email and we will send you a reset link.',
    'forgotPwd.email': 'Email address',
    'forgotPwd.placeholder': 'you@email.com',
    'forgotPwd.cancel': 'Cancel',
    'forgotPwd.send': 'Send link',
    'forgotPwd.success': 'If an account with that email exists, you will receive a reset link shortly.',
    'forgotPwd.close': 'Close',
    'forgotPwd.error': 'Something went wrong. Please try again.',

    // Reset password page
    'resetPwd.title': 'New password',
    'resetPwd.subtitle': 'Choose a secure password for your account.',
    'resetPwd.password': 'New password',
    'resetPwd.confirmPassword': 'Confirm password',
    'resetPwd.submit': 'Save password',
    'resetPwd.submitting': 'Saving...',
    'resetPwd.success': 'Your password was updated. You can now sign in.',
    'resetPwd.goToLogin': 'Go to sign in',
    'resetPwd.errorMatch': 'Passwords do not match.',
    'resetPwd.errorLength': 'Password must be at least 8 characters.',
    'resetPwd.errorExpired': 'This link has expired. Please request a new reset link.',
    'resetPwd.errorInvalid': 'This link is not valid.',
    'resetPwd.errorGeneric': 'Something went wrong. Please try again.',
    'resetPwd.requestNew': 'Request a new link',

    // Register
    'register.title': 'Create account',
    'register.subtitle': 'Join Pooly and start creating surveys',
    'register.name': 'Name',
    'register.namePlaceholder': 'Your name',
    'register.email': 'Email address',
    'register.emailPlaceholder': 'you@email.com',
    'register.password': 'Password',
    'register.confirmPassword': 'Confirm password',
    'register.submit': 'Create account',
    'register.submitting': 'Creating account...',
    'register.hasAccount': 'Already have an account?',
    'register.loginLink': 'Sign in here',
    'register.errorPasswordLength': 'Password must be at least 8 characters.',
    'register.errorPasswordMatch': 'Passwords do not match',
    'register.errorUserExists': 'This username is already taken. Please try another.',
    'register.errorGeneric': 'Registration failed. Please try again.',
    'register.errorAutoLogin': 'Account created, but auto sign-in failed. Please sign in manually.',
    'register.errorEmailExists': 'This email is already registered. Did you forget your password?',
    'register.send_verification': 'Send verification link',
    'register.send_verification_submitting': 'Sending...',
    'register.check_email': 'We sent you a verification link. Check your inbox and click the link to continue. The link expires in 30 minutes.',
    'register.check_email_sent_to': 'We sent a verification link to {{email}}.',
    'register.token_verifying': 'Verifying link...',
    'register.token_expired': 'This link has expired. Please request a new one.',
    'register.token_invalid': 'This link is not valid or has already been used.',
    'register.verified_email_label': 'Verified email',
    'register.request_new_link': 'Request a new link',
    'register.complete_title': 'Complete your registration',

    // Admin Dashboard
    'admin.loading': 'Loading your dashboard...',
    'admin.hello': 'Hello, {{username}}',
    'admin.subtitle': "Here's what your customers are saying today.",
    'admin.statTotal': 'Surveys',
    'admin.statResponses': 'Responses',
    'admin.statActive': 'Active',
    'admin.statAvg': 'Avg. responses',
    'admin.errorLoad': 'Could not load your events.',
    'admin.errorDemo': 'Showing demo data',
    'admin.deleteSuccess': 'The survey was deleted successfully.',
    'admin.deleteError': 'Could not delete the survey. Please try again.',
    'admin.deleteErrorGeneric': 'Error deleting the survey. Please try again.',
    'admin.sectionTitle': 'Your surveys',
    'admin.survey': 'survey',
    'admin.surveys': 'surveys',
    'admin.project': 'project',
    'admin.projects': 'projects',
    'admin.newSurvey': 'New survey',
    'admin.importResults': 'Import results',
    'admin.suggestedAction': 'Suggested action',
    'admin.viewTopic': 'View topic',
    'admin.viewInsights': 'View insights',
    'admin.entryCreateTitle': 'New Survey',
    'admin.entryCreateDesc': 'Create and share an online survey directly in Pooly.',
    'admin.entryImportTitle': 'Import Results',
    'admin.entryImportDesc': 'Upload your reviews from Excel or CSV files',
    'admin.importedFrom': 'Imported from {{source}}',
    'admin.emptyTitle': 'No projects yet',
    'admin.emptyDesc': 'Create a new survey or import existing results to get AI analysis.',
    'admin.createFirst': 'Create my first survey',
    'admin.tapHint': 'Tap to view details',
    'admin.deleteModalTitle': 'Delete survey',
    'admin.deleteModalMessage': 'Are you sure you want to delete the survey "{{name}}"?',
    'admin.deleteWarning': 'This action cannot be undone. The following will be deleted:',
    'admin.deleteItem1': 'All survey questions',
    'admin.deleteItem2': 'All received responses ({{count}})',
    'admin.deleteItem3': 'All generated analysis reports',
    'admin.cancel': 'Cancel',
    'admin.delete': 'Delete',
    'admin.deleting': 'Deleting...',
    'admin.edit': 'Edit',
    'admin.duplicate': 'Duplicate',
    'admin.pause': 'Pause',
    'admin.resume': 'Resume',
    'admin.paused': 'Paused',
    'admin.duplicateSuccess': 'Survey duplicated successfully.',
    'admin.duplicateError': 'Could not duplicate the survey. Please try again.',
    'admin.pauseSuccess': 'Survey paused.',
    'admin.resumeSuccess': 'Survey resumed.',
    'admin.pauseError': 'Could not change status. Please try again.',

    // Event status labels
    'status.ended': 'Ended',
    'status.lastDay': 'Last day',
    'status.closing': 'Closing soon',
    'status.active': 'Active',
    'status.endedDays': 'Ended {{days}} days ago',
    'status.endsToday': 'Ends today',
    'status.daysLeft': '{{days}} days left',
    'status.alwaysOpen': 'Always open',
    'status.alwaysOpenText': 'No end date',

    // Event Details
    'eventDetails.loading': 'Loading event details...',
    'eventDetails.back': '← Back to dashboard',
    'eventDetails.refresh': 'Refresh responses',
    'eventDetails.endDate': 'Ends: {{date}}',
    'eventDetails.totalResponses': '{{count}} total responses',
    'eventDetails.analyzeTitle': 'Analyze with AI',
    'eventDetails.analyzing': 'Analyzing...',
    'eventDetails.shareTitle': 'Share link',
    'eventDetails.shareSubtitle': 'Share this link with your customers',
    'eventDetails.shareGenerating': 'Generating link...',
    'eventDetails.shareCopy': 'Copy',
    'eventDetails.shareCopied': '✓ Copied',
    'eventDetails.shareHint': 'Responses are completely anonymous. Your customers do not need to create an account.',
    'eventDetails.importTitle': 'Data source',
    'eventDetails.importSubtitle': 'This project uses imported responses and converges into the same AI analysis flow.',
    'eventDetails.importSource': 'Source',
    'eventDetails.importFile': 'File',
    'eventDetails.importRows': 'Imported responses',
    'eventDetails.importDate': 'Upload date',
    'eventDetails.importSourceFallback': 'Manual upload',
    'eventDetails.importFileFallback': 'File unavailable',
    'eventDetails.importDateFallback': 'Not recorded',
    'eventDetails.importNoPreview': 'There is no response preview yet. Once the backend processes the file, responses will appear here grouped by question or column.',
    'eventDetails.tabOverview': 'Recommendations',
    'eventDetails.tabInsights': 'Cluster Analysis',
    'eventDetails.tabTrends': 'Trends',
    'eventDetails.tabResponses': 'Responses',
    'eventDetails.tabReports': 'AI Reports',
    'eventDetails.tabCharts': 'Charts',
    'eventDetails.tabStatus': 'Status',
    'eventDetails.noResponses': 'No responses yet.',
    'eventDetails.responses': 'responses',
    'eventDetails.errorLoad': 'Could not load event details.',

    // Reports tab
    'reports.title': 'Response Analysis',
    'reports.subtitle': '{{count}} categories identified by AI',
    'reports.subtitleEmpty': 'Reports will appear here after analysis',
    'reports.refresh': '↻ Refresh',
    'reports.loading': 'Loading...',
    'reports.loadingState': 'Loading reports...',
    'reports.error': 'Could not load reports.',
    'reports.errorDemo': 'Showing demo data',
    'reports.emptyTitle': 'No reports available',
    'reports.emptyDesc': 'Run an AI analysis to get insights from the responses.',
    'reports.analyzeBtn': 'Analyze with AI',
    'reports.generated': 'Generated: {{date}}',
    'reports.examples': 'Examples:',
    'reports.mentions': 'mentions',
    'reports.ofTotal': 'of total',

    // Charts tab
    'charts.title': 'Trend Charts',
    'charts.barTitle': 'Top detected issues',
    'charts.pieTitle': 'Sentiment distribution',
    'charts.percentage': 'Percentage',
    'charts.noData': 'No data to display. Run an AI analysis first.',
    'charts.exportBtn': 'Export PDF',
    'charts.exportingBtn': 'Generating...',

    // Sentiment / Urgency
    'sentiment.positive': 'Positive',
    'sentiment.negative': 'Negative',
    'sentiment.neutral': 'Neutral',
    'urgency.high': 'High',
    'urgency.medium': 'Medium',
    'urgency.low': 'Low',
    'urgency.label': 'Urgency: {{level}}',

    // Jobs / Status tab
    'jobs.title': 'Analysis Status',
    'jobs.subtitle': '{{count}} jobs registered',
    'jobs.subtitleEmpty': 'Analysis jobs will appear here',
    'jobs.loading': 'Loading jobs...',
    'jobs.error': 'Unable to retrieve information at this time.',
    'jobs.emptyTitle': 'No jobs registered',
    'jobs.emptyDesc': 'When you start an AI analysis, you can monitor its progress here.',
    'jobs.colId': 'ID',
    'jobs.colStatus': 'Status',
    'jobs.colMessage': 'Message',
    'jobs.colStarted': 'Started',
    'jobs.colUpdated': 'Finished',
    'jobs.statusCompleted': 'Completed',
    'jobs.statusRunning': 'Running',
    'jobs.statusError': 'Error',

    // Analyze modal
    'analyzeModal.title': 'Start AI analysis',
    'analyzeModal.cancel': 'Cancel',
    'analyzeModal.confirm': 'Start analysis',
    'analyzeModal.statusSuccess': 'Analysis started successfully! You can monitor progress in the Status section.',
    'analyzeModal.statusError': 'Error starting analysis. Please try again.',

    // Create Event
    'create.back': '← Back to dashboard',
    'create.title': 'Create new survey',
    'create.step': 'Step {{step}} of 2',
    'create.step1Label': 'Survey details',
    'create.step2Label': 'Add questions',
    'create.name': 'Survey name',
    'create.namePlaceholder': 'e.g. Post-purchase feedback Q3 2026',
    'create.description': 'Description',
    'create.descPlaceholder': 'Describe the purpose of this survey...',
    'create.endDate': 'End date',
    'create.endDateToggle': 'Set an end date',
    'create.next': 'Next: Add questions',
    'create.errorNoDate': 'Please select an end date for the survey.',
    'create.errorPastDate': 'The end date must be in the future.',
    'create.questionsLabel': 'Survey questions',
    'create.questionsHint': 'Write your questions and define the expected type of response.',
    'create.questionPlaceholder': 'Write question {{num}}',
    'create.questionTypeOpen': 'Free text',
    'create.questionTypeMultiple': 'Multiple choice',
    'create.questionTypeNumeric': 'Numeric',
    'create.questionTypeDate': 'Date',
    'create.addQuestion': '+ Add another question',
    'create.questionRequired': 'Required',
    'create.questionOptional': 'Optional',
    'create.optionPlaceholder': 'Option {{num}}',
    'create.addOption': '+ Add option',
    'create.prev': 'Previous',
    'create.preview': 'Preview',
    'create.submit': 'Create survey',
    'create.submitting': 'Creating...',
    'create.errorNoQuestions': 'Please add at least one question.',
    'create.errorMultipleOptions': 'Multiple choice questions need at least 2 options.',
    'create.errorGeneric': 'Error creating the survey.',
    'create.successToast': 'Survey created successfully!',
    'create.draftRestoredBanner': 'We recovered a draft you didn\'t finish. You can continue where you left off.',
    'create.draftDiscard': 'Discard draft',
    'create.draftSaved': 'Draft saved',
    'tips.step1.title': 'Tips for your survey',
    'tips.step1.tip1.title': 'Clear, specific title',
    'tips.step1.tip1.desc': 'A good title tells your customer what it\'s about. E.g.: "Tell us about your purchase" instead of "Survey".',
    'tips.step1.tip2.title': 'Motivating description',
    'tips.step1.tip2.desc': 'Tell your customer their opinion drives real decisions: which products to improve, how to fix delivery, what to change.',
    'tips.step1.tip3.title': 'The right moment',
    'tips.step1.tip3.desc': 'Send it while the experience is fresh: right after delivery, support, or a return.',
    'tips.step1.highlight': 'Surveys with clear descriptions get 40% more participation.',
    'tips.step2.title': 'Create effective questions',
    'tips.step2.tip1.title': 'Open-ended questions',
    'tips.step2.tip1.desc': 'They allow detailed responses that our AI can analyze to find patterns and trends.',
    'tips.step2.tip2.title': 'Avoid bias',
    'tips.step2.tip2.desc': "Don't lead responses. \"How was the shipping?\" is better than \"Don't you think shipping was slow?\"",
    'tips.step2.tip3.title': 'Pick the right type',
    'tips.step2.tip3.desc': 'Free text for opinions, Multiple choice for fixed categories, Numeric for measurements like ages or scores, and Date for events.',
    'tips.step2.highlight': 'Our AI analyzes responses to automatically identify topics, sentiment, and priorities.',
    'tips.examples.title': 'Examples of good questions',
    'tips.examples.item1': 'What made you hesitate before buying?',
    'tips.examples.item2': 'What would you improve about the product or delivery?',
    'tips.examples.item3': 'Why did you decide to return your order?',

    // Edit Event / Questions
    'editEvent.editBtn': 'Edit Event',
    'editEvent.saveBtn': 'Save changes',
    'editEvent.cancelBtn': 'Cancel',
    'editEvent.saving': 'Saving...',
    'editEvent.addQuestion': 'Add question',
    'editEvent.saveSuccess': 'Changes saved successfully.',
    'editEvent.saveError': 'Error saving information.',
    'editEvent.newQuestionsLabel': 'New questions',
    'editEvent.existingQuestionsLabel': 'Existing questions',
    'editEvent.questionPlaceholder': 'Write new question {{num}}',
    'editEvent.pageTitle': 'Edit survey',
    'editEvent.back': '← Back',
    'editEvent.sectionInfo': 'General information',
    'editEvent.sectionQuestions': 'Questions',
    'editEvent.name': 'Survey name',
    'editEvent.description': 'Description',
    'editEvent.endDate': 'Closing date',
    'editEvent.noEndDate': 'No closing date',
    'editEvent.welcomeLabel': 'Welcome screen',
    'editEvent.completionLabel': 'Thank you screen',
    'editEvent.welcomePlaceholder': 'Welcome message (Markdown)',
    'editEvent.completionPlaceholder': 'Closing message (Markdown)',
    'editEvent.deleteQuestion': 'Delete question',
    'editEvent.backendNote': 'Some changes require backend updates.',

    // Settings
    'settings.back': '← Back to dashboard',
    'settings.title': 'Settings',
    'settings.subtitle': 'Your account details',
    'settings.sectionTitle': 'User information',
    'settings.username': 'Username',
    'settings.email': 'Email address',
    'settings.role': 'Role',
    'settings.roleDefault': 'User',
    'settings.notificationsSection': 'Email notifications',
    'settings.notificationsLabel': 'Receive news and offers from Pooly.mx',
    'settings.notificationsDesc': 'We will send you product updates, news and special offers.',
    'settings.notificationsSaved': 'Preference saved.',
    'settings.notificationsError': 'Failed to save. Please try again.',

    // Landing page
    'landing.nav.how': 'How it works',
    'landing.nav.pricing': 'Pricing',
    'landing.nav.faq': 'FAQ',
    'landing.nav.demoBtn': 'Book a demo',
    'landing.hero.title1': 'Hear what your customers really think —',
    'landing.hero.title2': 'without reading every response.',
    'landing.hero.sub': 'Pooly analyzes your customers\' open-ended feedback with AI and gives you themes, sentiment, and action recommendations in under 5 minutes.',
    'landing.hero.cta': 'Book your free demo',
    'landing.hero.note': 'For early adopters only — access from $19 USD/mo',
    'landing.problem.eyebrow': 'The problem',
    'landing.problem.title': 'Sound familiar?',
    'landing.problem.subtitle': 'Whether you run an online store or a physical location, the problem is the same.',
    'landing.problem.physical.label': 'Physical business',
    'landing.problem.physical.p1.title': "You don't know if the experience is consistent",
    'landing.problem.physical.p1.body': "Your customer at location 3 has a different experience than location 1 — and you find out too late.",
    'landing.problem.physical.p2.title': "The customer doesn't tell you anything in the moment",
    'landing.problem.physical.p2.body': "They smile at checkout, but don't come back. And you don't know why.",
    'landing.problem.physical.p3.title': "Your reviews are 4 stars and you don't know why they're not 5",
    'landing.problem.physical.p3.body': 'Comments arrive scattered and no one really analyzes them.',
    'landing.problem.ecommerce.label': 'E-commerce',
    'landing.problem.ecommerce.p1.title': 'Abandoned carts with no explanation',
    'landing.problem.ecommerce.p1.body': "Your customer showed up, looked, and left — without telling you anything. No one explains why.",
    'landing.problem.ecommerce.p2.title': "Reviews that say nothing useful",
    'landing.problem.ecommerce.p2.body': '3-star reviews that just say "ok" or 5 stars saying "arrived fast." No real information.',
    'landing.problem.ecommerce.p3.title': "Hours reading support without seeing the pattern",
    'landing.problem.ecommerce.p3.body': "Tickets, messages, DMs — and you still don't know which problem comes up the most.",
    'landing.fit.eyebrow': 'Is this for you?',
    'landing.fit.title': "Let's see in 30 seconds",
    'landing.fit.subtitle': 'Pooly works for two kinds of business.',
    'landing.fit.col1.title': 'Yes, if you have a physical presence',
    'landing.fit.col1.subtitle': 'Gym, restaurant, spa, clinic, retail...',
    'landing.fit.col1.li1': "You have customers visiting your business and want to know what they think without waiting for a review",
    'landing.fit.col1.li2': 'You operate more than one location and consistency of experience keeps you up at night',
    'landing.fit.col1.li3': 'Your customers are repeat customers and silent churn is your biggest threat',
    'landing.fit.col1.li4': 'You make operational decisions and want data, not just intuition',
    'landing.fit.col2.title': 'Yes, if you sell online',
    'landing.fit.col2.subtitle': 'Shopify, WooCommerce, Mercado Libre, VTEX...',
    'landing.fit.col2.li1': 'You get customer feedback but reading it all would take a full day',
    'landing.fit.col2.li2': 'You want to know what makes a customer buy for the first time — and what brings them back',
    'landing.fit.col2.li3': 'Your reviews and support tickets hold valuable information nobody is using',
    'landing.fit.col2.li4': 'You want to improve conversion and retention with real data, not guesses',
    'landing.hiw.eyebrow': 'How it works',
    'landing.hiw.title': 'This is how Pooly works',
    'landing.hiw.s1.title': 'Create your survey in 2 minutes',
    'landing.hiw.s1.body': 'No technical setup. Choose the moment: post-purchase, post-delivery, returns, or support.',
    'landing.hiw.s2.title': 'Your customer answers from their phone',
    'landing.hiw.s2.body': 'No account needed, in seconds, from the link you send them.',
    'landing.hiw.s3.title': 'Pooly analyzes everything automatically',
    'landing.hiw.s3.body': 'Emerging themes, sentiment, urgency, and concrete action recommendations.',
    'landing.platforms.eyebrow': 'Compatibility',
    'landing.platforms.title': 'For brands that sell on:',
    'landing.platforms.other': '…and any other platform',
    'landing.platforms.body': 'If you run an online store and want to understand your customers without needing an analytics team — Pooly is for you.',
    'landing.pricing.eyebrow': 'Price',
    'landing.pricing.title': 'Early Adopter Access',
    'landing.pricing.priceSuffix': 'USD / month',
    'landing.pricing.note': 'Price locked in for life',
    'landing.pricing.li1': 'Unlimited surveys',
    'landing.pricing.li2': 'AI analysis (themes, sentiment, urgency)',
    'landing.pricing.li3': 'Automatic action recommendations',
    'landing.pricing.li4': 'Direct support from the Pooly team',
    'landing.pricing.spots': 'Only {{n}} of 20 spots left',
    'landing.pricing.btn': 'I want early access',
    'landing.faq.eyebrow': 'FAQ',
    'landing.faq.title': 'Frequently asked questions',
    'landing.faq.q1': 'Does it work with Shopify / Mercado Libre / VTEX / WooCommerce?',
    'landing.faq.a1': 'Yes. Pooly works with any platform — no technical integration required. You create the survey in Pooly and share the link with your customers through whatever channel you prefer: email, WhatsApp, social media, or post-purchase.',
    'landing.faq.q2': 'Do my customers need to create an account to respond?',
    'landing.faq.a2': 'No. Your customer opens the link, answers in free text, and that\'s it — no sign-up, no apps, from their phone in under a minute.',
    'landing.faq.q3': 'How long does it take to set up the first survey?',
    'landing.faq.a3': 'Less than 2 minutes. You choose the survey type (post-purchase, returns, support), customize the questions if you want, and get the link to share.',
    'landing.faq.q4': 'What happens with my customers\' data?',
    'landing.faq.a4': 'Your customers\' data is yours. Pooly processes responses with AI to generate the analysis, but doesn\'t use it to train models or share it with third parties.',
    'landing.faq.q5': 'How is it different from Typeform or Google Forms?',
    'landing.faq.a5': 'Typeform and Google Forms collect responses — you still have to read and analyze them. Pooly closes the loop: it analyzes automatically, identifies patterns, and tells you what to do. The difference is between having data and having decisions.',
    'landing.finalcta.title': 'Got 20 minutes?',
    'landing.finalcta.body': 'We\'ll show you how Pooly works with real data from your store.',
    'landing.finalcta.btn': 'Book a free demo',
    'landing.footer.tagline': 'Voice-of-customer for e-commerce. From open-ended answers to decisions, in minutes.',
    'landing.footer.login': 'Log in',
    'landing.footer.copy': '© 2026 Pooly · All rights reserved.',
    'landing.footer.privacy': 'Privacy policy',
    'landing.footer.terms': 'Terms of use',

    // Public Gallery
    'gallery.badge': 'Voice-of-customer for e-commerce',
    'gallery.heroTitle1': 'Turn your customers\' voices into',
    'gallery.heroTitle2': 'actionable insights',
    'gallery.heroDesc': 'Ask your customers open-ended questions and get automatic AI analysis in under 5 minutes. Themes, sentiment, urgency, and recommendations — without reading every response.',
    'gallery.ctaStart': 'Get started free',
    'gallery.ctaLogin': 'I already have an account',
    'gallery.howTitle': 'How it works',
    'gallery.howDesc': 'Three simple steps to turn customer feedback into business decisions.',
    'gallery.step1Title': 'Create your survey',
    'gallery.step1Desc': 'Define the open-ended questions you want to ask your customers: post-purchase, post-delivery, returns, or product validation.',
    'gallery.step2Title': 'Share the link',
    'gallery.step2Desc': 'Distribute the link via email, WhatsApp, or QR. Customers answer in seconds from their phone, no account needed.',
    'gallery.step3Title': 'Get insights',
    'gallery.step3Desc': 'Our AI groups responses, identifies emerging topics, and analyzes sentiment automatically.',
    'gallery.aiTitle': 'Powered by artificial intelligence',
    'gallery.aiDesc': 'Advanced Natural Language Processing technology to understand what your customers really think.',
    'gallery.feature1Title': 'Automatic discovery',
    'gallery.feature1Desc': 'Translates hundreds of individual responses into clear categories without predefining them. AI finds the patterns for you.',
    'gallery.feature2Title': 'Priority analysis',
    'gallery.feature2Desc': 'Ranks topics by importance, sentiment, and urgency. Decide on product, shipping, and retention with real customer data.',
    'gallery.feature3Title': 'Multilingual',
    'gallery.feature3Desc': 'Support for 50+ languages. Receive responses in any language and get unified, consistent analysis.',
    'gallery.useCasesTitle': 'Use cases',
    'gallery.useCasesDesc': 'Every moment of your customer\'s journey is a chance to listen.',
    'gallery.useCase1Title': 'Post-purchase survey',
    'gallery.useCase1Desc': 'Understand what made shoppers hesitate before paying and what convinced them. Optimize conversion with your customers\' own words.',
    'gallery.useCase2Title': 'Returns & cancellations',
    'gallery.useCase2Desc': 'Find out why customers return orders or cancel subscriptions, in their own words. Reduce churn by fixing the real cause.',
    'gallery.useCase3Title': 'Product validation',
    'gallery.useCase3Desc': 'Test new ideas and products directly with your customers and iterate fast. Insights that power your catalog.',
    'gallery.statLang': 'Languages supported',
    'gallery.statAi': 'Intelligent analysis',
    'gallery.statAnon': 'Anonymous and secure',
    'gallery.ctaTitle': 'Start listening to your customers',
    'gallery.ctaDesc': 'Create your first survey in minutes. No credit card required.',
    'gallery.ctaBtn': 'Create free account',
    'gallery.footer': '© 2026 Pooly. Your customers\' voice, turned into decisions.',

    // Public Survey
    'survey.loading': 'Loading survey...',
    'survey.notFound': 'Survey not found',
    'survey.notFoundDesc': 'The link you followed is not valid or the survey is no longer available.',
    'survey.pausedTitle': 'Survey unavailable',
    'survey.pausedDesc': 'This survey is temporarily paused. Please try again later.',
    'survey.previewBanner': 'PREVIEW MODE',
    'survey.previewBannerDesc': 'This survey has not been published. Responses will not be saved.',
    'survey.previewClose': 'Close preview',
    'survey.previewSubmitDisabled': 'Submission disabled in preview',
    'survey.goToPooly': 'Go to Pooly',
    'survey.progressBadge': '{{answered}} of {{total}}',
    'survey.question': 'Question {{num}}',
    'survey.placeholder': 'Write your answer here...',
    'survey.anonymous': 'Your responses are anonymous and secure',
    'survey.submit': 'Submit',
    'survey.submitting': 'Submitting...',
    'survey.successTitle': 'Thanks for your feedback!',
    'survey.successDesc': 'Your responses were recorded successfully.',
    'survey.successNote': 'What you shared helps the brand make better decisions for you.',
    'survey.errorAtLeastOne': 'Please answer at least one question.',
    'survey.errorMaxChars': 'Answers {{nums}} cannot exceed 500 characters.',
    'survey.errorSubmit': 'Error submitting responses.',
    'survey.placeholderNumeric': 'e.g. 25',
    'survey.placeholderDate': 'Select a date',
    'survey.errorLoad': 'Could not load the survey.',
    'survey.welcomeStart': 'Start survey',
    'survey.stepCounter': '{{step}}/{{total}}',
    'survey.introCta': 'Start — takes {{min}} min',
    'survey.introDefaultDesc': '{{count}} quick, anonymous questions. Your opinion helps decide what to really improve.',
    'survey.trustAnonymous': 'Anonymous',
    'survey.trustNoAccount': 'No account needed',
    'survey.next': 'Next',
    'survey.continueBlock': 'Continue',
    'survey.poweredBy': 'Powered by',
    'source.online': 'Online',
    'source.imported': 'Imported',
    'import.back': '← Back to dashboard',
    'import.title': 'Import results',
    'import.subtitle': 'Bring in responses you already collected in Excel and run them through the same Pooly analysis engine without recreating the survey.',
    'import.name': 'Project name',
    'import.namePlaceholder': 'e.g. Product reviews Q2 2026',
    'import.description': 'Description',
    'import.descriptionPlaceholder': 'Explain what this file contains and which decision it should inform.',
    'import.fileLabel': 'Responses file',
    'import.fileTitle': 'Select your file',
    'import.fileHelp': 'Drag your file here or choose it from your computer. Supported formats: .xlsx, .xls, .csv — headers in the first row.',
    'import.fileBrowse': 'Browse files',
    'import.fileEmpty': 'No file selected',
    'import.cancel': 'Cancel',
    'import.submit': 'Import and continue',
    'import.submitting': 'Importing...',
    'import.sidebarTitle': 'How to prepare your file',
    'import.tip1Title': 'One row per response',
    'import.tip1Desc': 'Each row should represent a single response or completed submission.',
    'import.tip2Title': 'Open text first',
    'import.tip2Desc': 'Pooly works best with columns that contain open feedback, comments, or observations.',
    'import.tip3Title': 'Keep the format simple',
    'import.tip3Desc': 'Avoid multiple sheets, merged cells, or decorative headers in the MVP.',
    'import.expectedTitle': 'Expected format',
    'import.expected1': 'Clear column headers in the first row.',
    'import.expected2': 'A single sheet per file.',
    'import.expected3': 'Open-text columns so the model can detect themes and sentiment.',
    'import.highlight': 'After upload, the project moves into the same reports, charts, and PDF export flow as a survey created inside Pooly.',
    'import.errorNoFile': 'Select a file to continue.',
    'import.errorInvalidFile': 'Unsupported format. Use .xlsx, .xls, or .csv.',
    'import.errorNoColumns': 'Add at least one column before importing.',
    'import.errorSubmit': 'Could not import the file. Please verify the expected format and try again.',
    'import.errorMissingProject': 'The import finished without returning a valid project.',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem('pooly_language') || 'es'
  );

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('pooly_language', lang);
  };

  const t = (key, vars = {}) => {
    let str = translations[language]?.[key] ?? key;
    Object.entries(vars).forEach(([k, v]) => {
      str = str.replace(new RegExp(`\\{\\{${k}\\}\\}`, 'g'), String(v));
    });
    return str;
  };

  const locale = language === 'es' ? 'es-MX' : 'en-US';

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, locale }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
