import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext(null);

const translations = {
  es: {
    // Navbar
    'navbar.controlPanel': 'Panel de control',
    'navbar.login': 'Iniciar sesión',
    'navbar.register': 'Comenzar',
    'navbar.logout': 'Cerrar sesión',
    'lang.es': 'Español',
    'lang.en': 'English',

    // Auth - social & legal
    'auth.socialDivider': 'o continúa con',
    'auth.google': 'Continuar con Google',
    'auth.googleError': 'Error al iniciar sesión con Google. Inténtalo de nuevo.',
    'register.legalPrefix': 'Al registrarte, aceptas los',
    'register.termsLink': 'Términos de uso',
    'register.legalAnd': 'y el',
    'register.privacyLink': 'Aviso de privacidad',
    'register.legalSuffix': '. También aceptas recibir novedades del producto y promociones especiales por correo electrónico. Puedes cancelar estos correos en cualquier momento desde tu página de Preferencias de cuenta.',

    // Login
    'login.title': 'Bienvenido de nuevo',
    'login.subtitle': 'Inicia sesión para gestionar tus encuestas',
    'login.username': 'Usuario',
    'login.usernamePlaceholder': 'Tu nombre de usuario',
    'login.password': 'Contraseña',
    'login.forgotPassword': '¿Olvidaste tu contraseña?',
    'login.submit': 'Iniciar sesión',
    'login.submitting': 'Iniciando sesión...',
    'login.noAccount': '¿No tienes cuenta?',
    'login.registerLink': 'Regístrate aquí',
    'login.error': 'Error al iniciar sesión. Verifica tus credenciales.',

    // Forgot password
    'forgotPwd.title': 'Recuperar contraseña',
    'forgotPwd.description': 'Ingresa tu correo y te enviaremos un enlace para restablecer tu contraseña.',
    'forgotPwd.email': 'Correo electrónico',
    'forgotPwd.placeholder': 'tu@correo.com',
    'forgotPwd.cancel': 'Cancelar',
    'forgotPwd.send': 'Enviar enlace',
    'forgotPwd.success': 'Si existe una cuenta con ese correo, recibirás un enlace en breve.',
    'forgotPwd.close': 'Cerrar',

    // Register
    'register.title': 'Crear cuenta',
    'register.subtitle': 'Únete a Pooly y comienza a crear encuestas',
    'register.username': 'Usuario',
    'register.usernamePlaceholder': 'Elige un nombre de usuario',
    'register.email': 'Correo electrónico',
    'register.emailPlaceholder': 'tu@correo.com',
    'register.password': 'Contraseña',
    'register.confirmPassword': 'Confirmar contraseña',
    'register.submit': 'Crear cuenta',
    'register.submitting': 'Creando cuenta...',
    'register.hasAccount': '¿Ya tienes cuenta?',
    'register.loginLink': 'Inicia sesión aquí',
    'register.errorPasswordMatch': 'Las contraseñas no coinciden',
    'register.errorUserExists': 'Este usuario ya existe. Intenta con otro nombre de usuario.',
    'register.errorGeneric': 'Error en el registro. Inténtalo de nuevo.',
    'register.errorAutoLogin': 'Cuenta creada, pero el inicio de sesión automático falló. Por favor inicia sesión manualmente.',

    // Admin Dashboard
    'admin.loading': 'Cargando tu panel de control...',
    'admin.hello': 'Hola, {{username}}',
    'admin.subtitle': 'Gestiona tus encuestas y analiza las respuestas de tu comunidad.',
    'admin.statTotal': 'Encuestas totales',
    'admin.statResponses': 'Respuestas totales',
    'admin.statActive': 'Encuestas activas',
    'admin.statAvg': 'Promedio respuestas',
    'admin.errorLoad': 'No se pudieron cargar tus eventos.',
    'admin.errorDemo': 'Mostrando datos de demostración',
    'admin.deleteSuccess': 'La encuesta se eliminó correctamente.',
    'admin.deleteError': 'No se pudo eliminar la encuesta. Intenta de nuevo.',
    'admin.deleteErrorGeneric': 'Error al eliminar la encuesta. Intenta de nuevo.',
    'admin.sectionTitle': 'Mis encuestas',
    'admin.survey': 'encuesta',
    'admin.surveys': 'encuestas',
    'admin.newSurvey': 'Nueva encuesta',
    'admin.emptyTitle': 'Aún no tienes encuestas',
    'admin.emptyDesc': 'Crea tu primera encuesta para comenzar a recolectar opiniones de tu comunidad.',
    'admin.createFirst': 'Crear mi primera encuesta',
    'admin.tapHint': 'Toca para ver detalles',
    'admin.deleteModalTitle': 'Eliminar encuesta',
    'admin.deleteModalMessage': '¿Estás seguro de que deseas eliminar la encuesta "{{name}}"?',
    'admin.deleteWarning': 'Esta acción no se puede deshacer. Se eliminarán:',
    'admin.deleteItem1': 'Todas las preguntas de la encuesta',
    'admin.deleteItem2': 'Todas las respuestas recibidas ({{count}})',
    'admin.deleteItem3': 'Todos los reportes de análisis generados',
    'admin.cancel': 'Cancelar',
    'admin.delete': 'Eliminar',
    'admin.deleting': 'Eliminando...',

    // Event status labels
    'status.ended': 'Finalizada',
    'status.lastDay': 'Último día',
    'status.closing': 'Por cerrar',
    'status.active': 'Activa',
    'status.endedDays': 'Terminó hace {{days}} días',
    'status.endsToday': 'Termina hoy',
    'status.daysLeft': '{{days}} días restantes',

    // Event Details
    'eventDetails.loading': 'Cargando detalles del evento...',
    'eventDetails.back': '← Volver al panel',
    'eventDetails.endDate': 'Finaliza: {{date}}',
    'eventDetails.totalResponses': '{{count}} respuestas totales',
    'eventDetails.analyzeTitle': 'Analizar con IA',
    'eventDetails.analyzing': 'Analizando...',
    'eventDetails.shareTitle': 'Enlace para compartir',
    'eventDetails.shareSubtitle': 'Comparte este enlace con los participantes',
    'eventDetails.shareGenerating': 'Generando enlace...',
    'eventDetails.shareCopy': 'Copiar',
    'eventDetails.shareCopied': '✓ Copiado',
    'eventDetails.shareHint': 'Las respuestas son completamente anónimas. Los participantes no necesitan crear cuenta.',
    'eventDetails.tabResponses': 'Respuestas',
    'eventDetails.tabReports': 'Reportes IA',
    'eventDetails.tabStatus': 'Status',
    'eventDetails.noResponses': 'Sin respuestas aún.',
    'eventDetails.responses': 'respuestas',
    'eventDetails.errorLoad': 'No se pudieron cargar los detalles del evento.',

    // Reports tab
    'reports.title': 'Análisis de Respuestas',
    'reports.subtitle': '{{count}} categorías identificadas por IA',
    'reports.subtitleEmpty': 'Los reportes aparecerán aquí después del análisis',
    'reports.refresh': '↻ Actualizar',
    'reports.loading': 'Cargando...',
    'reports.loadingState': 'Cargando reportes...',
    'reports.error': 'No se pudieron cargar los reportes.',
    'reports.errorDemo': 'Mostrando datos de demostración',
    'reports.emptyTitle': 'Sin reportes disponibles',
    'reports.emptyDesc': 'Genera un análisis con IA para obtener insights de las respuestas.',
    'reports.analyzeBtn': 'Analizar con IA',
    'reports.generated': 'Generado: {{date}}',
    'reports.examples': 'Ejemplos:',
    'reports.mentions': 'menciones',
    'reports.ofTotal': 'del total',

    // Sentiment / Urgency
    'sentiment.positive': 'Positivo',
    'sentiment.negative': 'Negativo',
    'sentiment.neutral': 'Neutral',
    'urgency.high': 'Alta',
    'urgency.medium': 'Media',
    'urgency.low': 'Baja',
    'urgency.label': 'Urgencia: {{level}}',

    // Jobs / Status tab
    'jobs.title': 'Estado de Análisis',
    'jobs.subtitle': '{{count}} trabajos registrados',
    'jobs.subtitleEmpty': 'Los trabajos de análisis aparecerán aquí',
    'jobs.loading': 'Cargando trabajos...',
    'jobs.error': 'No es posible recuperar la información en este momento.',
    'jobs.emptyTitle': 'Sin trabajos registrados',
    'jobs.emptyDesc': 'Cuando inicies un análisis con IA, podrás ver su progreso aquí.',
    'jobs.colId': 'ID',
    'jobs.colStatus': 'Estado',
    'jobs.colMessage': 'Mensaje',
    'jobs.colStarted': 'Iniciado',
    'jobs.colUpdated': 'Actualizado',
    'jobs.statusCompleted': 'Completado',
    'jobs.statusRunning': 'En proceso',
    'jobs.statusError': 'Error',

    // Analyze modal
    'analyzeModal.title': 'Iniciar análisis con IA',
    'analyzeModal.cancel': 'Cancelar',
    'analyzeModal.confirm': 'Iniciar análisis',
    'analyzeModal.statusSuccess': '¡Análisis iniciado exitosamente! Puedes monitorear el progreso en la sección Status.',
    'analyzeModal.statusError': 'Error al iniciar el análisis. Intenta de nuevo.',

    // Create Event
    'create.back': '← Volver al panel',
    'create.title': 'Crear nueva encuesta',
    'create.step': 'Paso {{step}} de 2',
    'create.step1Label': 'Detalles de la encuesta',
    'create.step2Label': 'Agregar preguntas',
    'create.name': 'Nombre de la encuesta',
    'create.namePlaceholder': 'ej. Movilidad Urbana 2026',
    'create.description': 'Descripción',
    'create.descPlaceholder': 'Describe el propósito de esta encuesta...',
    'create.endDate': 'Fecha de cierre',
    'create.next': 'Siguiente: Agregar preguntas',
    'create.errorNoDate': 'Por favor selecciona una fecha de cierre para la encuesta.',
    'create.errorPastDate': 'La fecha de cierre debe ser una fecha futura.',
    'create.questionsLabel': 'Preguntas de la encuesta',
    'create.questionsHint': 'Escribe preguntas abiertas para que los participantes puedan responder libremente.',
    'create.questionPlaceholder': 'Escribe la pregunta {{num}}',
    'create.addQuestion': '+ Agregar otra pregunta',
    'create.questionRequired': 'Obligatoria',
    'create.questionOptional': 'Opcional',
    'create.prev': 'Anterior',
    'create.submit': 'Crear encuesta',
    'create.submitting': 'Creando...',
    'create.errorNoQuestions': 'Por favor agrega al menos una pregunta.',
    'create.errorGeneric': 'Error al crear la encuesta.',
    'tips.step1.title': 'Consejos para tu encuesta',
    'tips.step1.tip1.title': 'Título claro y específico',
    'tips.step1.tip1.desc': 'Un buen título ayuda a los participantes a entender el tema. Ej: "Movilidad Urbana 2026" en lugar de "Encuesta".',
    'tips.step1.tip2.title': 'Descripción motivadora',
    'tips.step1.tip2.desc': 'Explica por qué es importante participar y cómo se usarán las respuestas para tomar decisiones.',
    'tips.step1.tip3.title': 'Tiempo suficiente',
    'tips.step1.tip3.desc': 'Da al menos 1-2 semanas para que los participantes puedan responder con calma.',
    'tips.step1.highlight': 'Las encuestas con descripciones claras tienen 40% más participación.',
    'tips.step2.title': 'Crea preguntas efectivas',
    'tips.step2.tip1.title': 'Preguntas abiertas',
    'tips.step2.tip1.desc': 'Permiten respuestas detalladas que nuestra IA puede analizar para encontrar patrones y tendencias.',
    'tips.step2.tip2.title': 'Evita sesgos',
    'tips.step2.tip2.desc': 'No induzcas respuestas. "¿Qué opinas del transporte?" es mejor que "¿No crees que el transporte es malo?"',
    'tips.step2.tip3.title': 'Una idea por pregunta',
    'tips.step2.tip3.desc': 'Divide preguntas complejas. Es más fácil analizar "¿Qué medio usas?" y "¿Qué mejorarías?" por separado.',
    'tips.step2.highlight': 'Nuestra IA analiza las respuestas para identificar temas, sentimiento y prioridades automáticamente.',
    'tips.examples.title': 'Ejemplos de buenas preguntas',
    'tips.examples.item1': '¿Cuál es el principal problema que enfrentas con...?',
    'tips.examples.item2': '¿Qué cambiarías si pudieras...?',
    'tips.examples.item3': '¿Cómo te afecta actualmente...?',

    // Edit Event / Questions
    'editEvent.editBtn': 'Editar Evento',
    'editEvent.saveBtn': 'Guardar',
    'editEvent.cancelBtn': 'Cancelar',
    'editEvent.saving': 'Guardando...',
    'editEvent.addQuestion': '+ Agregar pregunta',
    'editEvent.saveSuccess': 'Guardado con éxito',
    'editEvent.saveError': 'Error al guardar la información',
    'editEvent.newQuestionsLabel': 'Nuevas preguntas',
    'editEvent.existingQuestionsLabel': 'Preguntas existentes',
    'editEvent.questionPlaceholder': 'Escribe la nueva pregunta {{num}}',

    // Settings
    'settings.back': '← Volver al panel',
    'settings.title': 'Configuración',
    'settings.subtitle': 'Detalles de tu cuenta',
    'settings.sectionTitle': 'Información de usuario',
    'settings.username': 'Nombre de usuario',
    'settings.email': 'Correo electrónico',
    'settings.role': 'Rol',
    'settings.roleDefault': 'Usuario',

    // Landing page
    'landing.nav.product': 'Producto',
    'landing.nav.how': 'Cómo funciona',
    'landing.nav.demo': 'Demo',
    'landing.nav.pricing': 'Precios',
    'landing.hero.kicker': 'Análisis de retroalimentación con IA',
    'landing.hero.title1': 'Recolecta opiniones abiertas.',
    'landing.hero.title2': 'La IA encuentra los insights.',
    'landing.hero.sub': 'Pooly te permite crear encuestas de preguntas abiertas, distribuirlas a tu audiencia y obtener análisis automático de las respuestas — sin leer cada respuesta manualmente.',
    'landing.hero.cta1': 'Empezar gratis',
    'landing.hero.cta2': 'Ver cómo funciona',
    'landing.hero.note': 'Sin tarjeta de crédito · Acceso inmediato',
    'landing.hero.stat1.value': '< 2 min',
    'landing.hero.stat1.label': 'Para publicar tu primera encuesta',
    'landing.hero.stat1.trend': 'Insights en minutos',
    'landing.hero.stat2.label': 'Análisis automático',
    'landing.hero.stat2.trend': 'Sin categorías predefinidas',
    'landing.f1.eyebrow': 'Recolección de retroalimentación',
    'landing.f1.title': 'Crea encuestas de preguntas abiertas en minutos',
    'landing.f1.body': 'Define las preguntas que quieres hacer a tu comunidad, clientes o equipo. Sin opciones predefinidas — las personas responden con sus propias palabras, lo que permite recolectar retroalimentación genuina y sin sesgos.',
    'landing.f1.li1': 'Preguntas abiertas para respuestas auténticas',
    'landing.f1.li2': 'Enlace único de participación anónima',
    'landing.f1.li3': 'Compatible con cualquier dispositivo',
    'landing.f1.li4': 'Marca la fecha de cierre y gestiona tus encuestas activas',
    'landing.f1.cta': 'Crear mi primera encuesta →',
    'landing.midcta.h3': '¿Quieres ver Pooly en acción?',
    'landing.midcta.p': 'Agenda una demo y te mostramos cómo convertir retroalimentación abierta en insights accionables en minutos.',
    'landing.midcta.btn': 'Solicitar demo →',
    'landing.f2.eyebrow': 'Análisis de IA',
    'landing.f2.title': 'La IA lee y organiza las respuestas por ti',
    'landing.f2.body': 'Una vez que tienes respuestas, Pooly aplica Procesamiento de Lenguaje Natural (PLN) para agrupar automáticamente las respuestas en temas, detectar el sentimiento predominante e identificar las prioridades más frecuentes — sin que tengas que leer cada respuesta una por una.',
    'landing.f2.li1': 'Agrupación automática de respuestas por tema',
    'landing.f2.li2': 'Detección de sentimiento positivo, negativo y neutro',
    'landing.f2.li3': 'Reporte de urgencia y prioridades clave',
    'landing.f2.cta': 'Solicitar demo →',
    'landing.stats.l1': 'Encuesta publicada',
    'landing.stats.l2': 'Análisis automático',
    'landing.stats.l3': 'Respuestas anónimas',
    'landing.stats.l4': 'Sin categorías previas',
    'landing.stats.v1': '< 2 min',
    'landing.stats.v2': 'Con 1 clic',
    'landing.stats.v3': '100%',
    'landing.stats.v4': 'Preguntas abiertas',
    'landing.f4.eyebrow': 'Hecho para equipos',
    'landing.f4.title': 'Colabora en tus encuestas y comparte los insights',
    'landing.f4.body': 'Gestiona tus encuestas, revisa las respuestas de tu comunidad y ejecuta el análisis de IA cuando estés listo. Comparte los reportes con tu equipo o tus stakeholders para tomar decisiones informadas.',
    'landing.f4.li1': 'Panel de control para gestionar todas tus encuestas',
    'landing.f4.li2': 'Visualiza respuestas individuales en tiempo real',
    'landing.f4.li3': 'Ejecuta el análisis de IA con un solo clic',
    'landing.f4.cta': 'Solicitar demo',
    'landing.hiw.eyebrow': 'Cómo funciona',
    'landing.hiw.title': 'De la pregunta al insight en tres pasos',
    'landing.hiw.body': 'Sin instalación, sin configuraciones complejas. Crea tu encuesta, comparte el enlace y deja que la IA haga el trabajo pesado.',
    'landing.hiw.s1.title': 'Crea tu encuesta',
    'landing.hiw.s1.body': 'Define el nombre, descripción y las preguntas abiertas que quieres hacer. El enlace de participación se genera automáticamente.',
    'landing.hiw.s2.title': 'Comparte y recolecta',
    'landing.hiw.s2.body': 'Distribuye el enlace único por email, redes sociales o QR. Los participantes responden de forma anónima desde cualquier dispositivo.',
    'landing.hiw.s3.title': 'Obtén tus insights',
    'landing.hiw.s3.body': 'Activa el análisis de IA con un clic. Pooly agrupa las respuestas, identifica temas, sentimiento y prioridades en un reporte claro.',
    'landing.hiw.cta': 'Crear cuenta gratis →',
    'landing.demo.eyebrow': 'Piloto y demo',
    'landing.demo.title': 'Estamos en fase piloto',
    'landing.demo.body': 'Pooly está en etapa de pruebas con organizaciones seleccionadas. Si quieres ser de los primeros en usar la plataforma para tu equipo o comunidad, solicita acceso anticipado.',
    'landing.demo.btn': 'Solicitar acceso →',
    'landing.demo.note': 'O crea una cuenta gratuita y explora la plataforma por tu cuenta.',
    'landing.demo.register': 'Crear cuenta gratis',
    'landing.p.eyebrow': 'Acceso',
    'landing.p.title': 'Empieza gratis o solicita una demo',
    'landing.p.body': 'Explora la plataforma con una cuenta gratuita, o contáctanos para una demo personalizada.',
    'landing.p.free.plan': 'Cuenta gratuita',
    'landing.p.free.period': 'sin costo',
    'landing.p.free.desc': 'Crea una cuenta, explora la plataforma y lanza tu primera encuesta sin necesidad de tarjeta de crédito.',
    'landing.p.free.li1': 'Acceso completo a la plataforma',
    'landing.p.free.li2': 'Crea encuestas de preguntas abiertas',
    'landing.p.free.li3': 'Distribuye tu enlace de participación',
    'landing.p.free.li4': 'Análisis de IA sobre tus respuestas',
    'landing.p.free.btn': 'Crear cuenta gratis',
    'landing.p.demo.plan': 'Demo personalizada',
    'landing.p.demo.badge': 'Recomendado',
    'landing.p.demo.price': 'Gratis',
    'landing.p.demo.period': 'sin compromiso',
    'landing.p.demo.desc': 'Te mostramos la plataforma en vivo, respondemos tus preguntas y definimos juntos cómo Pooly puede ayudar a tu organización.',
    'landing.p.demo.li1': 'Sesión en vivo con nuestro equipo',
    'landing.p.demo.li2': 'Caso de uso adaptado a tu contexto',
    'landing.p.demo.li3': 'Resolución de dudas en tiempo real',
    'landing.p.demo.li4': 'Acceso anticipado a nuevas funciones',
    'landing.p.demo.btn': 'Solicitar demo →',
    'landing.cta.title': 'Convierte la retroalimentación de tu comunidad en decisiones.',
    'landing.cta.body': 'Pooly está en fase piloto. Sé de los primeros en descubrir lo que tu comunidad realmente piensa.',
    'landing.cta.btn1': 'Crear cuenta gratis →',
    'landing.cta.btn2': 'Solicitar demo',
    'landing.footer.tagline': 'Análisis de retroalimentación abierta potenciado por inteligencia artificial.',
    'landing.footer.col1': 'Producto',
    'landing.footer.col2': 'Recursos',
    'landing.footer.col3': 'Empresa',
    'landing.footer.col4': 'Contacto',
    'landing.footer.p1': 'Crear encuesta',
    'landing.footer.p2': 'Análisis de IA',
    'landing.footer.p3': 'Panel de control',
    'landing.footer.p4': 'Precios',
    'landing.footer.r1': 'Cómo funciona',
    'landing.footer.r2': 'Casos de uso',
    'landing.footer.r3': 'Preguntas frecuentes',
    'landing.footer.r4': 'Estado del servicio',
    'landing.footer.l1': 'Acerca de Pooly',
    'landing.footer.l2': 'Blog',
    'landing.footer.l3': 'Empleos',
    'landing.footer.l4': 'Prensa',
    'landing.footer.a1': 'Contacto',
    'landing.footer.a2': 'Solicitar demo',
    'landing.footer.a3': 'Aviso de privacidad',
    'landing.footer.a4': 'Términos de servicio',
    'landing.footer.copy': '© 2025 Pooly. Todos los derechos reservados.',
    'landing.footer.privacy': 'Privacidad',
    'landing.footer.terms': 'Términos',
    'landing.footer.cookies': 'Cookies',

    // Public Gallery
    'gallery.badge': 'Plataforma de participación ciudadana',
    'gallery.heroTitle1': 'Transforma miles de voces en',
    'gallery.heroTitle2': 'insights accionables',
    'gallery.heroDesc': 'Crea encuestas, recolecta opiniones de tu comunidad y obtén análisis automático con IA. Descubre patrones, sentimientos y prioridades sin categorías predefinidas.',
    'gallery.ctaStart': 'Comenzar gratis',
    'gallery.ctaLogin': 'Ya tengo cuenta',
    'gallery.howTitle': 'Cómo funciona',
    'gallery.howDesc': 'Tres pasos simples para convertir la retroalimentación de tu comunidad en decisiones informadas.',
    'gallery.step1Title': 'Crea tu encuesta',
    'gallery.step1Desc': 'Define las preguntas abiertas que quieres hacer a tu comunidad. Sin límites de opciones predefinidas.',
    'gallery.step2Title': 'Comparte el enlace',
    'gallery.step2Desc': 'Distribuye el enlace único. Los participantes responden de forma anónima desde cualquier dispositivo.',
    'gallery.step3Title': 'Obtén insights',
    'gallery.step3Desc': 'Nuestra IA agrupa respuestas, identifica temas emergentes y analiza el sentimiento automáticamente.',
    'gallery.aiTitle': 'Potenciado por inteligencia artificial',
    'gallery.aiDesc': 'Tecnología avanzada de Procesamiento de Lenguaje para entender lo que tu comunidad realmente necesita.',
    'gallery.feature1Title': 'Descubrimiento automático',
    'gallery.feature1Desc': 'Traduce miles de voces individuales en categorías claras sin necesidad de definirlas previamente. La IA encuentra los patrones por ti.',
    'gallery.feature2Title': 'Análisis de prioridades',
    'gallery.feature2Desc': 'Clasifica los temas por importancia, sentimiento y urgencia. Toma decisiones basadas en datos reales de tu comunidad.',
    'gallery.feature3Title': 'Multilingüe',
    'gallery.feature3Desc': 'Soporte para más de 50 idiomas. Recibe respuestas en cualquier idioma y obtén análisis unificados y coherentes.',
    'gallery.useCasesTitle': 'Casos de uso',
    'gallery.useCasesDesc': 'Desde planeación urbana hasta investigación de mercado, Pooly se adapta a tus necesidades.',
    'gallery.useCase1Title': 'Planeación urbana',
    'gallery.useCase1Desc': 'Recolecta retroalimentación ciudadana sobre infraestructura, parques y servicios públicos. Visualiza el futuro de tu ciudad a través de la colaboración comunitaria.',
    'gallery.useCase2Title': 'Eventos y conferencias',
    'gallery.useCase2Desc': 'Entiende la satisfacción de los asistentes y recopila sugerencias de mejora. Desde conferencias hasta festivales, clarifica cada voz.',
    'gallery.useCase3Title': 'Investigación de producto',
    'gallery.useCase3Desc': 'Prueba nuevas ideas directamente con tu comunidad e itera rápidamente. Insights que impulsan innovación significativa.',
    'gallery.statLang': 'Idiomas soportados',
    'gallery.statAi': 'Análisis inteligente',
    'gallery.statAnon': 'Anónimo y seguro',
    'gallery.ctaTitle': 'Empieza a escuchar a tu comunidad',
    'gallery.ctaDesc': 'Crea tu primera encuesta en minutos. Sin tarjeta de crédito requerida.',
    'gallery.ctaBtn': 'Crear cuenta gratis',
    'gallery.footer': '© 2025 Pooly. Plataforma de participación ciudadana.',

    // Public Survey
    'survey.loading': 'Cargando encuesta...',
    'survey.notFound': 'Encuesta no encontrada',
    'survey.notFoundDesc': 'El enlace que seguiste no es válido o la encuesta ya no está disponible.',
    'survey.goToPooly': 'Ir a Pooly',
    'survey.progressBadge': '{{answered}} de {{total}}',
    'survey.question': 'Pregunta {{num}}',
    'survey.placeholder': 'Escribe tu respuesta aquí...',
    'survey.anonymous': 'Tus respuestas son anónimas y seguras',
    'survey.submit': 'Enviar',
    'survey.submitting': 'Enviando...',
    'survey.successTitle': '¡Gracias por participar!',
    'survey.successDesc': 'Tus respuestas han sido registradas exitosamente.',
    'survey.successNote': 'Tu opinión es valiosa y nos ayuda a tomar mejores decisiones.',
    'survey.errorAtLeastOne': 'Por favor responde al menos una pregunta.',
    'survey.errorMaxChars': 'Las respuestas {{nums}} no pueden superar los 500 caracteres.',
    'survey.errorSubmit': 'Error al enviar las respuestas.',
    'survey.errorLoad': 'No se pudo cargar la encuesta.',
  },

  en: {
    // Navbar
    'navbar.controlPanel': 'Control Panel',
    'navbar.login': 'Log in',
    'navbar.register': 'Get started',
    'navbar.logout': 'Log out',
    'lang.es': 'Español',
    'lang.en': 'English',

    // Auth - social & legal
    'auth.socialDivider': 'or continue with',
    'auth.google': 'Continue with Google',
    'auth.googleError': 'Failed to sign in with Google. Please try again.',
    'register.legalPrefix': 'By signing up, you agree to the',
    'register.termsLink': 'Terms of Use',
    'register.legalAnd': 'and',
    'register.privacyLink': 'Privacy Notice',
    'register.legalSuffix': '. You also agree to receive product news and special promotions via email. You can opt-out of these emails in your My Account Preferences page anytime.',

    // Login
    'login.title': 'Welcome back',
    'login.subtitle': 'Sign in to manage your surveys',
    'login.username': 'Username',
    'login.usernamePlaceholder': 'Your username',
    'login.password': 'Password',
    'login.forgotPassword': 'Forgot your password?',
    'login.submit': 'Sign in',
    'login.submitting': 'Signing in...',
    'login.noAccount': "Don't have an account?",
    'login.registerLink': 'Sign up here',
    'login.error': 'Login failed. Please check your credentials.',

    // Forgot password
    'forgotPwd.title': 'Reset password',
    'forgotPwd.description': 'Enter your email and we will send you a reset link.',
    'forgotPwd.email': 'Email address',
    'forgotPwd.placeholder': 'you@email.com',
    'forgotPwd.cancel': 'Cancel',
    'forgotPwd.send': 'Send link',
    'forgotPwd.success': 'If an account with that email exists, you will receive a reset link shortly.',
    'forgotPwd.close': 'Close',

    // Register
    'register.title': 'Create account',
    'register.subtitle': 'Join Pooly and start creating surveys',
    'register.username': 'Username',
    'register.usernamePlaceholder': 'Choose a username',
    'register.email': 'Email address',
    'register.emailPlaceholder': 'you@email.com',
    'register.password': 'Password',
    'register.confirmPassword': 'Confirm password',
    'register.submit': 'Create account',
    'register.submitting': 'Creating account...',
    'register.hasAccount': 'Already have an account?',
    'register.loginLink': 'Sign in here',
    'register.errorPasswordMatch': 'Passwords do not match',
    'register.errorUserExists': 'This username is already taken. Please try another.',
    'register.errorGeneric': 'Registration failed. Please try again.',
    'register.errorAutoLogin': 'Account created, but auto sign-in failed. Please sign in manually.',

    // Admin Dashboard
    'admin.loading': 'Loading your dashboard...',
    'admin.hello': 'Hello, {{username}}',
    'admin.subtitle': 'Manage your surveys and analyze your community responses.',
    'admin.statTotal': 'Total surveys',
    'admin.statResponses': 'Total responses',
    'admin.statActive': 'Active surveys',
    'admin.statAvg': 'Avg. responses',
    'admin.errorLoad': 'Could not load your events.',
    'admin.errorDemo': 'Showing demo data',
    'admin.deleteSuccess': 'The survey was deleted successfully.',
    'admin.deleteError': 'Could not delete the survey. Please try again.',
    'admin.deleteErrorGeneric': 'Error deleting the survey. Please try again.',
    'admin.sectionTitle': 'My surveys',
    'admin.survey': 'survey',
    'admin.surveys': 'surveys',
    'admin.newSurvey': 'New survey',
    'admin.emptyTitle': 'No surveys yet',
    'admin.emptyDesc': 'Create your first survey to start collecting opinions from your community.',
    'admin.createFirst': 'Create my first survey',
    'admin.tapHint': 'Tap to view details',
    'admin.deleteModalTitle': 'Delete survey',
    'admin.deleteModalMessage': 'Are you sure you want to delete the survey "{{name}}"?',
    'admin.deleteWarning': 'This action cannot be undone. The following will be deleted:',
    'admin.deleteItem1': 'All survey questions',
    'admin.deleteItem2': 'All received responses ({{count}})',
    'admin.deleteItem3': 'All generated analysis reports',
    'admin.cancel': 'Cancel',
    'admin.delete': 'Delete',
    'admin.deleting': 'Deleting...',

    // Event status labels
    'status.ended': 'Ended',
    'status.lastDay': 'Last day',
    'status.closing': 'Closing soon',
    'status.active': 'Active',
    'status.endedDays': 'Ended {{days}} days ago',
    'status.endsToday': 'Ends today',
    'status.daysLeft': '{{days}} days left',

    // Event Details
    'eventDetails.loading': 'Loading event details...',
    'eventDetails.back': '← Back to dashboard',
    'eventDetails.endDate': 'Ends: {{date}}',
    'eventDetails.totalResponses': '{{count}} total responses',
    'eventDetails.analyzeTitle': 'Analyze with AI',
    'eventDetails.analyzing': 'Analyzing...',
    'eventDetails.shareTitle': 'Share link',
    'eventDetails.shareSubtitle': 'Share this link with participants',
    'eventDetails.shareGenerating': 'Generating link...',
    'eventDetails.shareCopy': 'Copy',
    'eventDetails.shareCopied': '✓ Copied',
    'eventDetails.shareHint': 'Responses are completely anonymous. Participants do not need to create an account.',
    'eventDetails.tabResponses': 'Responses',
    'eventDetails.tabReports': 'AI Reports',
    'eventDetails.tabStatus': 'Status',
    'eventDetails.noResponses': 'No responses yet.',
    'eventDetails.responses': 'responses',
    'eventDetails.errorLoad': 'Could not load event details.',

    // Reports tab
    'reports.title': 'Response Analysis',
    'reports.subtitle': '{{count}} categories identified by AI',
    'reports.subtitleEmpty': 'Reports will appear here after analysis',
    'reports.refresh': '↻ Refresh',
    'reports.loading': 'Loading...',
    'reports.loadingState': 'Loading reports...',
    'reports.error': 'Could not load reports.',
    'reports.errorDemo': 'Showing demo data',
    'reports.emptyTitle': 'No reports available',
    'reports.emptyDesc': 'Run an AI analysis to get insights from the responses.',
    'reports.analyzeBtn': 'Analyze with AI',
    'reports.generated': 'Generated: {{date}}',
    'reports.examples': 'Examples:',
    'reports.mentions': 'mentions',
    'reports.ofTotal': 'of total',

    // Sentiment / Urgency
    'sentiment.positive': 'Positive',
    'sentiment.negative': 'Negative',
    'sentiment.neutral': 'Neutral',
    'urgency.high': 'High',
    'urgency.medium': 'Medium',
    'urgency.low': 'Low',
    'urgency.label': 'Urgency: {{level}}',

    // Jobs / Status tab
    'jobs.title': 'Analysis Status',
    'jobs.subtitle': '{{count}} jobs registered',
    'jobs.subtitleEmpty': 'Analysis jobs will appear here',
    'jobs.loading': 'Loading jobs...',
    'jobs.error': 'Unable to retrieve information at this time.',
    'jobs.emptyTitle': 'No jobs registered',
    'jobs.emptyDesc': 'When you start an AI analysis, you can monitor its progress here.',
    'jobs.colId': 'ID',
    'jobs.colStatus': 'Status',
    'jobs.colMessage': 'Message',
    'jobs.colStarted': 'Started',
    'jobs.colUpdated': 'Updated',
    'jobs.statusCompleted': 'Completed',
    'jobs.statusRunning': 'Running',
    'jobs.statusError': 'Error',

    // Analyze modal
    'analyzeModal.title': 'Start AI analysis',
    'analyzeModal.cancel': 'Cancel',
    'analyzeModal.confirm': 'Start analysis',
    'analyzeModal.statusSuccess': 'Analysis started successfully! You can monitor progress in the Status section.',
    'analyzeModal.statusError': 'Error starting analysis. Please try again.',

    // Create Event
    'create.back': '← Back to dashboard',
    'create.title': 'Create new survey',
    'create.step': 'Step {{step}} of 2',
    'create.step1Label': 'Survey details',
    'create.step2Label': 'Add questions',
    'create.name': 'Survey name',
    'create.namePlaceholder': 'e.g. Urban Mobility 2026',
    'create.description': 'Description',
    'create.descPlaceholder': 'Describe the purpose of this survey...',
    'create.endDate': 'End date',
    'create.next': 'Next: Add questions',
    'create.errorNoDate': 'Please select an end date for the survey.',
    'create.errorPastDate': 'The end date must be in the future.',
    'create.questionsLabel': 'Survey questions',
    'create.questionsHint': 'Write open-ended questions so participants can answer freely.',
    'create.questionPlaceholder': 'Write question {{num}}',
    'create.addQuestion': '+ Add another question',
    'create.questionRequired': 'Required',
    'create.questionOptional': 'Optional',
    'create.prev': 'Previous',
    'create.submit': 'Create survey',
    'create.submitting': 'Creating...',
    'create.errorNoQuestions': 'Please add at least one question.',
    'create.errorGeneric': 'Error creating the survey.',
    'tips.step1.title': 'Tips for your survey',
    'tips.step1.tip1.title': 'Clear, specific title',
    'tips.step1.tip1.desc': 'A good title helps participants understand the topic. E.g.: "Urban Mobility 2026" instead of "Survey".',
    'tips.step1.tip2.title': 'Motivating description',
    'tips.step1.tip2.desc': 'Explain why participation matters and how responses will be used to make decisions.',
    'tips.step1.tip3.title': 'Enough time',
    'tips.step1.tip3.desc': 'Allow at least 1-2 weeks for participants to respond at their own pace.',
    'tips.step1.highlight': 'Surveys with clear descriptions get 40% more participation.',
    'tips.step2.title': 'Create effective questions',
    'tips.step2.tip1.title': 'Open-ended questions',
    'tips.step2.tip1.desc': 'They allow detailed responses that our AI can analyze to find patterns and trends.',
    'tips.step2.tip2.title': 'Avoid bias',
    'tips.step2.tip2.desc': "Don't lead responses. \"What do you think of transportation?\" is better than \"Don't you think transportation is bad?\"",
    'tips.step2.tip3.title': 'One idea per question',
    'tips.step2.tip3.desc': "Split complex questions. It's easier to analyze \"What transport do you use?\" and \"What would you improve?\" separately.",
    'tips.step2.highlight': 'Our AI analyzes responses to automatically identify topics, sentiment, and priorities.',
    'tips.examples.title': 'Examples of good questions',
    'tips.examples.item1': 'What is the main problem you face with...?',
    'tips.examples.item2': 'What would you change if you could...?',
    'tips.examples.item3': 'How does it currently affect you...?',

    // Edit Event / Questions
    'editEvent.editBtn': 'Edit Event',
    'editEvent.saveBtn': 'Save',
    'editEvent.cancelBtn': 'Cancel',
    'editEvent.saving': 'Saving...',
    'editEvent.addQuestion': '+ Add question',
    'editEvent.saveSuccess': 'Saved successfully',
    'editEvent.saveError': 'Error saving information',
    'editEvent.newQuestionsLabel': 'New questions',
    'editEvent.existingQuestionsLabel': 'Existing questions',
    'editEvent.questionPlaceholder': 'Write new question {{num}}',

    // Settings
    'settings.back': '← Back to dashboard',
    'settings.title': 'Settings',
    'settings.subtitle': 'Your account details',
    'settings.sectionTitle': 'User information',
    'settings.username': 'Username',
    'settings.email': 'Email address',
    'settings.role': 'Role',
    'settings.roleDefault': 'User',

    // Landing page
    'landing.nav.product': 'Product',
    'landing.nav.how': 'How it works',
    'landing.nav.demo': 'Demo',
    'landing.nav.pricing': 'Pricing',
    'landing.hero.kicker': 'AI-Powered Feedback Analysis',
    'landing.hero.title1': 'Collect open feedback.',
    'landing.hero.title2': 'AI finds the insights.',
    'landing.hero.sub': 'Pooly lets you create open-ended surveys, share them with your audience, and automatically analyze responses — without reading every answer manually.',
    'landing.hero.cta1': 'Get started free',
    'landing.hero.cta2': 'See how it works',
    'landing.hero.note': 'No credit card required · Instant access',
    'landing.hero.stat1.value': '< 2 min',
    'landing.hero.stat1.label': 'To publish your first survey',
    'landing.hero.stat1.trend': 'Insights in minutes',
    'landing.hero.stat2.label': 'Automatic analysis',
    'landing.hero.stat2.trend': 'No predefined categories',
    'landing.f1.eyebrow': 'Feedback Collection',
    'landing.f1.title': 'Create open-ended surveys in minutes',
    'landing.f1.body': 'Define the questions you want to ask your community, customers, or team. No predefined options — people answer in their own words, giving you genuine, unbiased feedback.',
    'landing.f1.li1': 'Open-ended questions for authentic responses',
    'landing.f1.li2': 'Unique anonymous participation link',
    'landing.f1.li3': 'Works on any device, no account needed for respondents',
    'landing.f1.li4': 'Set a closing date and manage all your active surveys',
    'landing.f1.cta': 'Create my first survey →',
    'landing.midcta.h3': 'Want to see Pooly in action?',
    'landing.midcta.p': 'Book a demo and we\'ll show you how to turn open feedback into actionable insights in minutes.',
    'landing.midcta.btn': 'Request a demo →',
    'landing.f2.eyebrow': 'AI Analysis',
    'landing.f2.title': 'AI reads and organizes responses for you',
    'landing.f2.body': 'Once responses are in, Pooly applies Natural Language Processing (NLP) to automatically cluster them into themes, detect the dominant sentiment, and surface the most frequent priorities — without you having to read each answer.',
    'landing.f2.li1': 'Automatic grouping of responses by topic',
    'landing.f2.li2': 'Positive, negative, and neutral sentiment detection',
    'landing.f2.li3': 'Urgency and key priorities report',
    'landing.f2.cta': 'Request a demo →',
    'landing.stats.l1': 'Survey published',
    'landing.stats.l2': 'Automatic analysis',
    'landing.stats.l3': 'Anonymous responses',
    'landing.stats.l4': 'No predefined categories',
    'landing.stats.v1': '< 2 min',
    'landing.stats.v2': '1 click',
    'landing.stats.v3': '100%',
    'landing.stats.v4': 'Open-ended',
    'landing.f4.eyebrow': 'Built for teams',
    'landing.f4.title': 'Manage surveys and share insights with your team',
    'landing.f4.body': 'Manage your surveys, review community responses, and run AI analysis when you\'re ready. Share reports with your team or stakeholders to make informed decisions.',
    'landing.f4.li1': 'Control panel to manage all your surveys',
    'landing.f4.li2': 'View individual responses in real time',
    'landing.f4.li3': 'Trigger AI analysis with a single click',
    'landing.f4.cta': 'Request a demo',
    'landing.hiw.eyebrow': 'How it works',
    'landing.hiw.title': 'From question to insight in three steps',
    'landing.hiw.body': 'No installation, no complex setup. Create your survey, share the link, and let AI do the heavy lifting.',
    'landing.hiw.s1.title': 'Create your survey',
    'landing.hiw.s1.body': 'Set a name, description, and the open-ended questions you want to ask. A participation link is generated automatically.',
    'landing.hiw.s2.title': 'Share & collect',
    'landing.hiw.s2.body': 'Distribute the unique link via email, social media, or QR code. Participants respond anonymously from any device.',
    'landing.hiw.s3.title': 'Get your insights',
    'landing.hiw.s3.body': 'Trigger AI analysis with one click. Pooly groups responses, identifies themes, sentiment, and priorities in a clear report.',
    'landing.hiw.cta': 'Create free account →',
    'landing.demo.eyebrow': 'Early access',
    'landing.demo.title': 'We\'re in pilot phase',
    'landing.demo.body': 'Pooly is being tested with selected organizations. If you want to be among the first to use the platform for your team or community, request early access.',
    'landing.demo.btn': 'Request access →',
    'landing.demo.note': 'Or create a free account and explore the platform on your own.',
    'landing.demo.register': 'Create free account',
    'landing.p.eyebrow': 'Access',
    'landing.p.title': 'Start free or request a demo',
    'landing.p.body': 'Explore the platform with a free account, or contact us for a personalized demo.',
    'landing.p.free.plan': 'Free account',
    'landing.p.free.period': 'no cost',
    'landing.p.free.desc': 'Create an account, explore the platform, and launch your first survey — no credit card needed.',
    'landing.p.free.li1': 'Full platform access',
    'landing.p.free.li2': 'Create open-ended surveys',
    'landing.p.free.li3': 'Distribute your participation link',
    'landing.p.free.li4': 'AI analysis on your responses',
    'landing.p.free.btn': 'Create free account',
    'landing.p.demo.plan': 'Personalized demo',
    'landing.p.demo.badge': 'Recommended',
    'landing.p.demo.price': 'Free',
    'landing.p.demo.period': 'no commitment',
    'landing.p.demo.desc': 'We show you the platform live, answer your questions, and figure out together how Pooly can help your organization.',
    'landing.p.demo.li1': 'Live session with our team',
    'landing.p.demo.li2': 'Use case tailored to your context',
    'landing.p.demo.li3': 'Real-time Q&A',
    'landing.p.demo.li4': 'Early access to new features',
    'landing.p.demo.btn': 'Request a demo →',
    'landing.cta.title': 'Turn your community\'s feedback into decisions.',
    'landing.cta.body': 'Pooly is in pilot phase. Be among the first to discover what your community really thinks.',
    'landing.cta.btn1': 'Create free account →',
    'landing.cta.btn2': 'Request a demo',
    'landing.footer.tagline': 'Open feedback analysis powered by artificial intelligence.',
    'landing.footer.col1': 'Product',
    'landing.footer.col2': 'Resources',
    'landing.footer.col3': 'Company',
    'landing.footer.col4': 'Contact',
    'landing.footer.p1': 'Create survey',
    'landing.footer.p2': 'AI Analysis',
    'landing.footer.p3': 'Control panel',
    'landing.footer.p4': 'Pricing',
    'landing.footer.r1': 'How it works',
    'landing.footer.r2': 'Use cases',
    'landing.footer.r3': 'FAQ',
    'landing.footer.r4': 'Service status',
    'landing.footer.l1': 'About Pooly',
    'landing.footer.l2': 'Blog',
    'landing.footer.l3': 'Careers',
    'landing.footer.l4': 'Press',
    'landing.footer.a1': 'Contact',
    'landing.footer.a2': 'Request demo',
    'landing.footer.a3': 'Privacy policy',
    'landing.footer.a4': 'Terms of service',
    'landing.footer.copy': '© 2025 Pooly. All rights reserved.',
    'landing.footer.privacy': 'Privacy',
    'landing.footer.terms': 'Terms',
    'landing.footer.cookies': 'Cookies',

    // Public Gallery
    'gallery.badge': 'Civic participation platform',
    'gallery.heroTitle1': 'Transform thousands of voices into',
    'gallery.heroTitle2': 'actionable insights',
    'gallery.heroDesc': 'Create surveys, collect opinions from your community, and get automatic AI analysis. Discover patterns, sentiments, and priorities without predefined categories.',
    'gallery.ctaStart': 'Get started free',
    'gallery.ctaLogin': 'I already have an account',
    'gallery.howTitle': 'How it works',
    'gallery.howDesc': 'Three simple steps to turn your community feedback into informed decisions.',
    'gallery.step1Title': 'Create your survey',
    'gallery.step1Desc': 'Define the open-ended questions you want to ask your community. No limits on predefined options.',
    'gallery.step2Title': 'Share the link',
    'gallery.step2Desc': 'Distribute the unique link. Participants respond anonymously from any device.',
    'gallery.step3Title': 'Get insights',
    'gallery.step3Desc': 'Our AI groups responses, identifies emerging topics, and analyzes sentiment automatically.',
    'gallery.aiTitle': 'Powered by artificial intelligence',
    'gallery.aiDesc': 'Advanced Natural Language Processing technology to understand what your community really needs.',
    'gallery.feature1Title': 'Automatic discovery',
    'gallery.feature1Desc': 'Translates thousands of individual voices into clear categories without predefining them. AI finds the patterns for you.',
    'gallery.feature2Title': 'Priority analysis',
    'gallery.feature2Desc': 'Ranks topics by importance, sentiment, and urgency. Make decisions based on real data from your community.',
    'gallery.feature3Title': 'Multilingual',
    'gallery.feature3Desc': 'Support for 50+ languages. Receive responses in any language and get unified, consistent analysis.',
    'gallery.useCasesTitle': 'Use cases',
    'gallery.useCasesDesc': 'From urban planning to market research, Pooly adapts to your needs.',
    'gallery.useCase1Title': 'Urban planning',
    'gallery.useCase1Desc': 'Collect citizen feedback on infrastructure, parks, and public services. Visualize the future of your city through community collaboration.',
    'gallery.useCase2Title': 'Events & conferences',
    'gallery.useCase2Desc': 'Understand attendee satisfaction and gather improvement suggestions. From conferences to festivals, amplify every voice.',
    'gallery.useCase3Title': 'Product research',
    'gallery.useCase3Desc': 'Test new ideas directly with your community and iterate quickly. Insights that drive meaningful innovation.',
    'gallery.statLang': 'Languages supported',
    'gallery.statAi': 'Intelligent analysis',
    'gallery.statAnon': 'Anonymous and secure',
    'gallery.ctaTitle': 'Start listening to your community',
    'gallery.ctaDesc': 'Create your first survey in minutes. No credit card required.',
    'gallery.ctaBtn': 'Create free account',
    'gallery.footer': '© 2025 Pooly. Civic participation platform.',

    // Public Survey
    'survey.loading': 'Loading survey...',
    'survey.notFound': 'Survey not found',
    'survey.notFoundDesc': 'The link you followed is not valid or the survey is no longer available.',
    'survey.goToPooly': 'Go to Pooly',
    'survey.progressBadge': '{{answered}} of {{total}}',
    'survey.question': 'Question {{num}}',
    'survey.placeholder': 'Write your answer here...',
    'survey.anonymous': 'Your responses are anonymous and secure',
    'survey.submit': 'Submit',
    'survey.submitting': 'Submitting...',
    'survey.successTitle': 'Thank you for your participation!',
    'survey.successDesc': 'Your responses have been recorded successfully.',
    'survey.successNote': 'Your opinion is valuable and helps us make better decisions.',
    'survey.errorAtLeastOne': 'Please answer at least one question.',
    'survey.errorMaxChars': 'Answers {{nums}} cannot exceed 500 characters.',
    'survey.errorSubmit': 'Error submitting responses.',
    'survey.errorLoad': 'Could not load the survey.',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem('pooly_language') || 'es'
  );

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('pooly_language', lang);
  };

  const t = (key, vars = {}) => {
    let str = translations[language]?.[key] ?? key;
    Object.entries(vars).forEach(([k, v]) => {
      str = str.replace(new RegExp(`\\{\\{${k}\\}\\}`, 'g'), String(v));
    });
    return str;
  };

  const locale = language === 'es' ? 'es-MX' : 'en-US';

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, locale }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
